
import React, { createContext, useContext, useState, useEffect } from "react";

// Define supported languages
export type SupportedLanguage = "sk" | "cs" | "en";

// Define the context type
type LanguageContextType = {
  language: SupportedLanguage;
  setLanguage: (language: SupportedLanguage) => void;
  t: (key: string) => string;
};

// Create the context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: "sk",
  setLanguage: () => {},
  t: (key: string) => key
});

// Translation data
const translations: Record<SupportedLanguage, Record<string, string>> = {
  sk: {
    // Slovak translations
    "welcome": "Vitajte na Majstri.com",
    "platform_description": "Platforma spájajúca profesionálnych remeselníkov s ľuďmi, ktorí hľadajú ich služby",
    "craftsman": "Som remeselník",
    "customer": "Som zákazník",
    "craftsman_desc": "Prezentujte svoje zručnosti a nájdite nových klientov vo vašom okolí",
    "customer_desc": "Nájdite spoľahlivých remeselníkov pre vaše projekty a vylepšenia domácnosti",
    "login": "Prihlásenie",
    "register": "Registrovať sa",
    "start": "Začať",
    "copyright": "Spájame remeselníkov a zákazníkov",
    
    // Navbar translations
    "home": "Domov",
    "categories": "Kategórie",
    "find_craftsman": "Nájsť remeselníka",
    "jobs": "Zákazky",
    "how_it_works": "Ako to funguje",
    "benefits": "Výhody",
    "messages": "Správy",
    "my_profile": "Môj profil",
    "sign_out": "Odhlásiť sa",
    "sign_in": "Prihlásiť sa",
    
    // Index page translations
    "professional_craftsmen": "Profesionálni remeselníci na jednom mieste",
    "find_best": "Nájdite najlepších",
    "craftsmen": "remeselníkov",
    "platform_connecting": "Platforma, ktorá spája profesionálnych remeselníkov a ľudí, ktorí potrebujú kvalitné služby remeselníkov priamo na Slovensku.",
    "search_profession": "Hľadajte podľa profesie alebo lokality...",
    "search": "Vyhľadať",
    "craftsmen_count": "500+ Remeselníkov",
    "cities_count": "100+ Miest",
    "categories_count": "20+ Kategórií",
    "find_best_craftsmen": "Nájdite najlepších remeselníkov",
    "search_name_craft": "Hľadajte podľa mena alebo remesla...",
    "enter_location": "Zadajte lokalitu...",
    "filter_category": "Filter podľa kategórie",
    "all_categories": "Všetky kategórie",
    "reset": "Reset",
    "view_all_categories": "Zobraziť všetky kategórie",
    "featured_profiles": "Zvýraznené profily sú zobrazené na vrchu",
    "error_loading": "Nastala chyba pri načítaní remeselníkov. Skúste to prosím neskôr.",
    "try_again": "Skúsiť znova",
    "no_craftsmen_found": "Nenašli sa žiadni remeselníci podľa vašich kritérií. Skúste upraviť vyhľadávanie.",
    "show_all_craftsmen": "Zobraziť všetkých remeselníkov",
    
    // About page
    "about_us": "O nás",
    
    // Footer translations
    "for_craftsmen": "Pre remeselníkov",
    "registration": "Registrácia",
    "pricing": "Cenník služieb",
    "registration_benefits": "Výhody registrácie",
    "for_customers": "Pre zákazníkov",
    "find_craftsmen": "Vyhľadať remeselníkov",
    "service_categories": "Kategórie služieb",
    "how_it_works_footer": "Ako to funguje",
    "reviews_ratings": "Hodnotenia a recenzie",
    "company": "Spoločnosť",
    "about_us_footer": "O nás",
    "contact": "Kontakt",
    "privacy": "Ochrana súkromia",
    "terms": "Podmienky používania",
    "all_rights_reserved": "Všetky práva vyhradené",
    
    // Profile translations
    "edit_profile": "Upraviť profil",
    "portfolio": "Portfólio",
    "reviews": "Hodnotenia",
    "calendar": "Kalendár",
    "contact_us": "Kontaktujte nás",
    "loading": "Načítavam...",
    "set_availability_profile": "Nastavte svoju dostupnosť v sekcii \"Kalendár dostupnosti\" vyššie na tejto stránke.",
    "contact_message": "Tu môžete vidieť dostupnosť remeselníka a kontaktovať ho prostredníctvom správy.",
    "send_message": "Poslať správu",
    "book_appointment": "Rezervácia termínu",
    "send_message_tab": "Poslať správu",
    "select_date": "1. Vyberte dátum",
    "select_time": "2. Vyberte čas",
    "request_details": "3. Detaily požiadavky",
    "job_description": "Popis práce*",
    "job_description_placeholder": "Opíšte, akú prácu potrebujete vykonať...",
    "address": "Adresa*",
    "address_placeholder": "Zadajte adresu, kde sa má práca vykonať",
    "estimated_price": "Predpokladaná cena",
    "estimated_price_placeholder": "Zadajte predpokladanú cenu",
    "add_photo": "Pridať fotografiu (voliteľné)",
    "upload_image": "Nahrať obrázok",
    "submit_request": "Odoslať požiadavku",
    "hourly_rate": "Hodinová sadzba",
    "loading_dates": "Načítavam dostupné termíny...",
    "craftsman_available": "Remeselník je dostupný v označené dni",
    "no_time_slots": "Žiadne dostupné termíny",
    "contact_craftsman_message": "Poslať správu remeselníkovi",
    "contact_message_desc": "Kliknite na tlačidlo nižšie pre kontaktovanie remeselníka priamo cez správy.",
    "go_to_messages": "Prejsť na správy",
    
    // Messages
    "messages_title": "Správy",
    "login_required": "Pre prístup k správam sa musíte prihlásiť",
    
    // Error messages
    "profile_access_error": "Chyba prístupu k profilu",
    "profile_access_message": "Nemáte oprávnenie na zobrazenie tohto profilu. Toto môže byť spôsobené nastaveniami Row Level Security (RLS) v databáze.",
    "rls_block_message": "Hoci ste prihlásený ako vlastník profilu, RLS pravidlá môžu blokovať prístup. Skúste sa odhlásiť a znova prihlásiť.",
    "create_profile_again": "Vytvoriť profil znova",
    "database_error": "Nastala chyba pripojenia k databáze",
    "database_error_message": "Nepodarilo sa spojiť s databázou. Skúste stránku obnoviť alebo to skúste znova neskôr.",
    "unexpected_error": "Nastala neočakávaná chyba",
    "try_again_later": "Skúste stránku obnoviť alebo to skúste znova neskôr.",
    "refresh_page": "Obnoviť stránku",
    
    // Benefits page
    "benefits_title": "Výhody pre remeselníkov",
    "benefit_1_title": "Nové obchodné príležitosti",
    "benefit_1_desc": "Získajte prístup k novým zákazníkom, ktorí aktívne hľadajú služby ako sú tie vaše.",
    "benefit_2_title": "Online prítomnosť",
    "benefit_2_desc": "Vytvorte si profesionálny profil, ktorý zvýši vašu viditeľnosť a dôveryhodnosť.",
    "benefit_3_title": "Flexibilný kalendár",
    "benefit_3_desc": "Spravujte svoju dostupnosť a prijímajte rezervácie, ktoré vyhovujú vášmu harmonogramu.",
    "benefit_4_title": "Hodnotenia a recenzie",
    "benefit_4_desc": "Budujte svoju reputáciu prostredníctvom spätnej väzby od spokojných zákazníkov.",
    "register_now": "Zaregistrujte sa teraz",
    "learn_more": "Dozvedieť sa viac",
    
    // Pricing page
    "pricing_title": "Cenník služieb",
    "basic_plan": "Základný plán",
    "basic_price": "0 € / mesiac",
    "basic_description": "Ideálne pre začínajúcich remeselníkov alebo tých, ktorí chcú vyskúšať platformu.",
    "premium_plan": "Premium plán",
    "premium_price": "19,99 € / mesiac",
    "premium_description": "Pre profesionálnych remeselníkov, ktorí chcú maximalizovať svoj potenciál.",
    "profile_feature": "Profesionálny profil",
    "portfolio_feature": "Fotografie portfólia",
    "reviews_feature": "Hodnotenia a recenzie",
    "basic_requests": "Obmedzené žiadosti",
    "premium_requests": "Neobmedzené žiadosti",
    "priority_listing": "Prioritné zobrazenie vo vyhľadávaní",
    "analytics_feature": "Analytika a reporty",
    "premium_support": "Prioritná podpora",
    "featured_profile": "Zvýraznený profil",
    "choose_plan": "Vybrať plán",
    "current_plan": "Váš aktuálny plán",
    
    // How it works page
    "how_it_works_title": "Ako to funguje",
    "step_1_customer": "1. Vyberte typ remeselníka",
    "step_1_customer_desc": "Prehliadajte kategórie a vyberte typ remeselníka, ktorého potrebujete.",
    "step_2_customer": "2. Kontaktujte remeselníka",
    "step_2_customer_desc": "Pošlite správu alebo si zarezervujte termín priamo cez platformu.",
    "step_3_customer": "3. Získajte kvalitnú službu",
    "step_3_customer_desc": "Užite si profesionálnu službu a potom zanechajte hodnotenie.",
    "step_1_craftsman": "1. Vytvorte si profil",
    "step_1_craftsman_desc": "Registrujte sa a vytvorte si profesionálny profil s portfóliom.",
    "step_2_craftsman": "2. Nastavte dostupnosť",
    "step_2_craftsman_desc": "Definujte, kedy ste k dispozícii pre nové zákazky.",
    "step_3_craftsman": "3. Získavajte zákazky",
    "step_3_craftsman_desc": "Buďte viditeľný a získavajte nových zákazníkov vo vašom okolí.",
    
    // Categories
    "carpentry": "Stolár",
    "electrician": "Elektrikár",
    "mason": "Murár",
    "plumber": "Inštalatér",
    "painter": "Maliar",
    "flooring": "Podlahár",
    "tinsmiths": "Klampiar",
    "locksmith": "Zámočník",
    "carpenter": "Tesár",
    "gardener": "Záhradník",
    "heating": "Kúrenár",
    "glazier": "Sklenár",
    
    // Terms of service page
    "terms_of_service": "Podmienky používania",
    "basic_information": "Základné informácie",
    "terms_intro": "Tieto podmienky používania upravujú vaše používanie služieb poskytovaných na Majstri.com. Ak máte akékoľvek otázky, kontaktujte nás na",
    "registration_age": "Vekové obmedzenie",
    "registration_age_desc": "Na registráciu a používanie našej platformy musíte mať najmenej 18 rokov alebo dovŕšiť vek plnoletosti vo vašej krajine.",
    "user_types": "Typy používateľov",
    "platform_user_types": "Naša platforma rozlišuje dva hlavné typy používateľov",
    "user_content": "Používateľský obsah",
    "user_content_desc": "Používatelia sú zodpovední za všetok obsah, ktorý nahrajú alebo zdieľajú na platforme, vrátane fotografií, recenzií a profilových informácií.",
    "ratings_reviews": "Hodnotenia a recenzie",
    "ratings_reviews_desc": "Zákazníci môžu zanechávať hodnotenia a recenzie na základe ich skúseností. Všetky recenzie musia byť úprimné a založené na skutočných skúsenostiach.",
    "bookings_communication": "Rezervácie a komunikácia",
    "bookings_communication_desc": "Všetky rezervácie a komunikácia by mali prebiehať prostredníctvom našej platformy, aby sme mohli zabezpečiť kvalitu služieb a riešiť prípadné problémy.",
    "responsibility": "Zodpovednosť",
    "responsibility_desc": "Platforma slúži iba ako sprostredkovateľ medzi remeselníkmi a zákazníkmi. Nenesieme zodpovednosť za kvalitu vykonaných prác ani za prípadné škody.",
    "payments": "Platby",
    "payments_desc": "Platby za služby sú dohodnuté priamo medzi remeselníkom a zákazníkom. Platforma môže účtovať poplatky za určité prémiové funkcie alebo služby.",
    "account_restrictions": "Obmedzenia účtu",
    "account_restrictions_desc": "Vyhradzujeme si právo obmedziť, pozastaviť alebo ukončiť účty, ktoré porušujú tieto podmienky alebo sú zapojené do podvodných aktivít.",
    "promotion_outside": "Propagácia mimo platformy",
    "promotion_outside_desc": "Remeselníci nesmú presmerovať zákazníkov mimo platformy s cieľom obísť poplatky alebo pravidlá platformy.",
    "data_protection": "Ochrana údajov",
    "data_protection_desc": "Spracúvame osobné údaje v súlade s našimi zásadami ochrany osobných údajov a príslušnými právnymi predpismi.",
    "analytics_cookies": "Analytika a cookies",
    "analytics_cookies_desc": "Používame cookies a analytické nástroje na zlepšenie našich služieb a zlepšenie používateľského zážitku.",
    "final_provisions": "Záverečné ustanovenia",
    "final_provisions_desc": "Vyhradzujeme si právo kedykoľvek zmeniť tieto podmienky používania. Aktuálnu verziu podmienok nájdete vždy na našom webe.",
    
    // New categories
    "drywaller": "Sádrokartonista",
    "tiler": "Obkladač",
    "wallpaper": "Tapetár",
    "chimney": "Kominár",
    "tv_tech": "TV/SAT Technik",
    "ac_tech": "Chladiar/Klimatizér",
    "furniture": "Montér nábytku",
    "auto": "Autoelektrikár / Automechanik",
    "metalwork": "Kovovýroba",
    "appliance": "Servis domácich spotrebičov",
    "it": "IT technik",
    "welder": "Zvárač",
    "cleaning": "Upratovacie služby",
    "woodcarving": "Drevorezbár / Umelecký stolár",
    "garden_architect": "Záhradný architekt",
    "window": "Okenár / Montáž okien a dverí",
    "solar": "Montér solárnych panelov",
    "scaffolder": "Lešenár",
    "masseur": "Masér / Masérka",
    "cosmetician": "Kozmetička",
    "nail": "Nechtový dizajnér / Manikérka",
    "pedicure": "Pedikér / Pedikérka",
    "makeup": "Vizážistka / Make-up artist",
    "hairdresser": "Kaderník / Kaderníčka",
    "barber": "Barber",
    "lash": "Lash & Brow artist",
    "tattoo": "Tetovanie / Permanentný make-up",
    "wellness": "Wellness terapeut",
    
    // Profile sections
    "profile_not_found": "Profil nebol nájdený",
    "create_profile": "Vytvoriť profil",
    "profile_creation_error": "Chyba pri vytváraní profilu",
    "profile_completion": "Dokončenie profilu",
    "user_type_question": "Aký typ používateľa ste?",
    "years_experience": "Roky skúseností",
    "specialization": "Špecializácia",
    "about_me": "O mne",
    "projects": "Projekty",
    "no_projects": "Zatiaľ nie sú pridané žiadne projekty",
    "add_project": "Pridať projekt",
    "portfolio_images": "Obrázky portfólia",
    "upload_portfolio": "Nahrať obrázky portfólia",
    "add_review": "Pridať hodnotenie",
    "select_craftsman": "Vyberte remeselníka",
    "write_review": "Napíšte recenziu",
    "rating": "Hodnotenie",
    "comment": "Komentár",
    "submit_review": "Odoslať hodnotenie",
    "edit_review": "Upraviť hodnotenie",
    "delete_review": "Vymazať hodnotenie",
    "reply": "Odpovedať",
    "edit_reply": "Upraviť odpoveď",
    "delete_reply": "Vymazať odpoveď",
    "save_changes": "Uložiť zmeny",
    "cancel": "Zrušiť",
    "availability_settings": "Nastavenia dostupnosti",
    "availability_calendar": "Kalendár dostupnosti",
    "set_time_slots": "Nastaviť časové sloty",
    "unavailable": "Nedostupný",
    "available_all_day": "Dostupný celý deň",
    "custom_hours": "Vlastné hodiny",
    "start_time": "Čas začiatku",
    "end_time": "Čas konca",
    "update_availability": "Aktualizovať dostupnosť",
    "availability_updated": "Dostupnosť bola aktualizovaná",
    "error_updating": "Chyba pri aktualizácii",
    
    // Reviews and profile sections
    "write_comment_placeholder": "Napíšte váš názor na prácu remeselníka...",
    "anonymous_customer": "Anonymný zákazník",
    "craftsman_response": "Odpoveď remeselníka",
    "no_reviews": "Zatiaľ nie sú žiadne hodnotenia",
    "be_first": "Buďte prvý, kto ohodnotí tohto remeselníka",
    "based_on": "Na základe",
    "ratings": "hodnotení",
    "personal_info": "Osobné informácie",
    "business_info": "Informácie o podnikaní",
    "location_label": "Lokalita",
    "phone_label": "Telefón",
    "email_label": "E-mail",
    "save_profile": "Uložiť profil",
    "saving": "Ukladám...",
    "profile_updated": "Profil bol aktualizovaný",
    "error_saving": "Chyba pri ukladaní profilu",
    
    // Chat and messages
    "conversation_with": "Konverzácia s",
    "new_message": "Nová správa",
    "select_recipient": "Vyberte príjemcu",
    "message_placeholder": "Napíšte správu...",
    "send": "Odoslať",
    "no_conversations": "Zatiaľ nemáte žiadne konverzácie",
    "start_conversation": "Začnite konverzáciu s remeselníkom alebo zákazníkom",
    "no_messages": "Zatiaľ nie sú žiadne správy",
    "type_message": "Napíšte správu pre začatie konverzácie",
    "message_sent": "Správa odoslaná",
    "error_sending": "Chyba pri odosielaní správy",
    "delete_conversation": "Vymazať konverzáciu",
    "archive_conversation": "Archivovať konverzáciu",
    "confirm_delete": "Naozaj chcete vymazať túto konverzáciu?",
    "yes_delete": "Áno, vymazať",
    
    // Privacy page translations
    "privacy_policy": "Zásady ochrany osobných údajov", 
    "last_updated": "Posledná aktualizácia",
    "may": "máj",
    "privacy_intro": "V týchto zásadách ochrany osobných údajov vám vysvetľujeme, ako zhromažďujeme, používame a chránime vaše osobné údaje pri používaní našej platformy.",
    "who_processes_data": "Kto spracúva vaše údaje",
    "data_controller_desc": "Správcom osobných údajov je prevádzkovateľ služby Majstri.com. Pre otázky ohľadom ochrany osobných údajov nás kontaktujte na",
    "what_data_processed": "Aké údaje spracúvame",
    "registration_data_desc": "Pri registrácii a používaní našej platformy zbierame nasledujúce údaje",
    "full_name": "Celé meno",
    "email_address": "E-mailová adresa",
    "phone_number": "Telefónne číslo",
    "city_of_residence": "Mesto bydliska",
    "data_purpose_desc": "Tieto údaje sú nevyhnutné na poskytovanie našich služieb, umožnenie komunikácie medzi používateľmi a zabezpečenie bezpečnosti na platforme.",
    "data_purpose": "Účel spracovania údajov",
    "data_processing_purposes": "Vaše osobné údaje spracúvame na nasledujúce účely",
    "registration_account": "Registrácia a správa účtu",
    "profile_creation": "Vytvorenie a prezentácia profilu",
    "contact_facilitation": "Uľahčenie kontaktu medzi remeselníkmi a zákazníkmi",
    "system_messages": "Zasielanie systémových správ",
    "platform_updates": "Informovanie o novinkách a aktualizáciách platformy",
    "data_access": "Prístup k vašim údajom",
    "data_access_desc": "K vašim údajom majú prístup len oprávnení zamestnanci a spolupracovníci, ktorí potrebujú tieto údaje na plnenie svojich pracovných povinností. Tretiím stranám poskytujeme údaje len v rozsahu nevyhnutnom na poskytovanie našich služieb alebo ak to vyžaduje zákon.",
    "data_retention": "Doba uchovávania údajov",
    "data_retention_desc": "Vaše osobné údaje uchovávame po dobu aktívneho užívania vašeho účtu a ešte po dobu 2 rokov po poslednej aktivite. Po uplynutí tejto doby sú údaje anonymizovené alebo vymazané.",
    "cookies_usage": "Používanie cookies",
    "cookies_usage_desc": "Naša webová stránka používa cookies na zlepšenie používateľského zážitku, analýzu návštevnosti a poskytovanie personalizovaných funkcií. Používaním našich služieb súhlasíte s používaním cookies v súlade s našimi zásadami.",
    "data_transfer": "Prenos údajov do zahraničia",
    "data_transfer_desc": "Vaše osobné údaje môžu byť prenášané a uchovávané na serveroch mimo vašej krajiny, ale vždy v súlade s príslušnými zákonmi o ochrane osobných údajov.",

    // Contact page translations
    "contact_question": "Máte otázky alebo spätnú väzbu?",
    "contact_feedback": "Váš názor je pre nás dôležitý. Ak máte akékoľvek otázky, návrhy alebo potrebujete pomoc, neváhajte nás kontaktovať.",
    "email_us": "Napíšte nám e-mail",
    "reply_soon": "Odpovieme vám čo najskôr, zvyčajne do 24 hodín.",
    "quick_contact_form": "Rýchly kontaktný formulár",
    "your_name": "Vaše meno",
    "name_placeholder": "Zadajte vaše meno",
    "your_email": "Váš e-mail",
    "subject": "Predmet",
    "subject_placeholder": "O čom chcete komunikovať",
    "message": "Správa",
    "message_placeholder": "Napíšte vašu správu tu...",
    
    // Reviews page translations
    "reviews_title": "Hodnotenia a recenzie",
    "why_reviews_important": "Prečo sú hodnotenia dôležité",
    "reviews_importance_1": "Hodnotenia pomáhajú budovať dôveru medzi remeselníkmi a zákazníkmi",
    "reviews_importance_2": "Hodnotenia prinášajú transparentnosť do služieb remeselníkov",
    "reviews_importance_3": "Hodnotenia motivujú k vyššej kvalite služieb",
    "fair_review_rules": "Pravidlá pre spravodlivé hodnotenia",
    "truthful_reviews": "Pravdivé hodnotenia",
    "truthful_reviews_desc": "Všetky hodnotenia musia byť založené na skutočných skúsenostiach so službou",
    "fake_reviews_prohibited": "Falošné hodnotenia sú zakázané",
    "fake_reviews_prohibited_desc": "Falošné alebo zavádzajúce hodnotenia budú odstránené",
    
    // Pricing page translations
    "pricing_subtitle": "Transparentná cenová politika pre všetkých používateľov",
    "platform_pricing_policy": "Cenová politika platformy",
    "platform_pricing_desc_1": "Majstri.com je v súčasnosti ",
    "platform_pricing_desc_2": "bezplatná platforma",
    "platform_pricing_desc_3": "pre všetkých remeselníkov aj zákazníkov. V budúcnosti plánujeme zaviesť",
    "platform_pricing_desc_4": "prémiové funkcie",
    "platform_pricing_desc_5": "pre remeselníkov, ktorí chcú zvýšiť svoju viditeľnosť a získať viac príležitostí.",
    "set_effective_pricing": "Ako stanoviť efektívne ceny služieb",
    "recommendations": "Odporúčania pre remeselníkov pri stanovení cien ich služieb:",
    "consider_costs": "Zvážte svoje náklady",
    "consider_costs_desc": "Do ceny zahrňte materiály, dopravu, čas a réžiu. Nezabudnite aj na dane a odvody.",
    "analyze_competition": "Analyzujte konkurenciu",
    "analyze_competition_desc": "Zistite si, aké ceny požadujú iní remeselníci za podobné služby vo vašej oblasti.",
    "be_transparent": "Buďte transparentní",
    "be_transparent_desc": "Jasne komunikujte, čo je zahrnuté v cene a aké sú potenciálne dodatočné náklady.",
    "specify_what_included": "Špecifikujte, čo je zahrnuté v cene",
    "specify_what_included_desc": "Podrobne uveďte, čo všetko zákazník za svoju platbu dostane.",
    "regular_discounts": "Zvážte pravidelné zľavy",
    "regular_discounts_desc": "Ponúkanie zliav pre verných zákazníkov alebo pri väčších zákazkách môže zvýšiť váš objem práce.",
    "more_pricing_questions": "Máte ďalšie otázky o cenách služieb?",
    
    // How it works page - additional translations
    "choose_category": "Vyberte kategóriu",
    "choose_category_desc": "Prechádzajte kategóriami a vyhľadajte typ remeselníka, ktorého potrebujete.",
    "view_profiles": "Prehliadajte profily",
    "view_profiles_desc": "Prehliadajte si detailné profily, hodnotenia a portfóliá remeselníkov.",
    "contact_craftsman": "Kontaktujte remeselníka",
    "contact_craftsman_desc": "Kontaktujte vybraného remeselníka priamo cez našu platformu.",
    "book_appointment_desc": "Zarezervujte si termín na základe dostupnosti remeselníka.",
    
    // Benefits page additions
    "professional_profile": "Profesionálny profil",
    "professional_profile_desc": "Vytvorte si profesionálny online profil, ktorý odprezentuje vaše zručnosti a portfólio práce",
    "new_customers": "Noví zákazníci",
    "new_customers_desc": "Získajte prístup k zákazníkom, ktorí aktívne hľadajú služby vo vašej oblasti",
    "availability_calendar_desc": "Spravujte svoj kalendár a umožnite zákazníkom rezervovať si termíny online",
    
    // Additional translations
    "review_moderation": "Moderovanie hodnotení",
    "review_moderation_desc": "Hodnotenia sú kontrolované, aby spĺňali naše pravidlá komunity",
    "rate_after_completion": "Ohodnoťte službu",
    "rate_after_completion_desc": "Po dokončení práce zanechajte hodnotenie a pomôžte ostatným zákazníkom.",
    "register_create_profile": "Vytvorte si profil",
    "register_create_profile_desc": "Zaregistrujte sa a vytvorte si profesionálny profil, ktorý ukáže vaše zručnosti.",
    "set_availability": "Nastavte dostupnosť",
    "set_availability_desc": "Nastavte svoj kalendár, aby zákazníci videli, kedy ste k dispozícii.",
    "communicate_with_customers": "Komunikujte so zákazníkmi",
    "communicate_with_customers_desc": "Odpovedajte na správy a požiadavky zákazníkov prostredníctvom platformy.",
    "gather_reviews": "Zbierajte hodnotenia",
    "gather_reviews_desc": "Získajte pozitívne hodnotenia a budujte svou online reputaciu.",
    "highlight_profile": "Zvýraznite svoj profil",
    "highlight_profile_desc": "Využite možnosti prémiových funkcií na zvýraznenie vášho profilu vo vyhľadávaní.",
    "more_questions": "Máte ďalšie otázky o tom, ako naša platforma funguje?",
    "customer_chat": "Chat so zákazníkmi",
    "customer_chat_desc": "Komunikujte so zákazníkmi priamo cez platformu bez potreby zdieľania osobných kontaktov",
    "profile_topping": "Zvýraznenie profilu",
    "profile_topping_desc": "Za poplatok zvýraznite svoj profil, aby sa zobrazoval na popredných miestach vo vyhľadávaní",
    "collecting_reviews": "Zbieranie recenzií",
    "collecting_reviews_desc": "Budujte si povesť prostredníctvom hodnotení a recenzií od spokojných zákazníkov",
    "easy_search": "Jednoduché vyhľadávanie",
    "easy_search_desc": "Rýchlo nájdite kvalifikovaných remeselníkov podľa lokality, odbornosti a hodnotenia",
    "transparent_profiles": "Transparentné profily",
    "transparent_profiles_desc": "Prezerajte si portfólio prác, hodnotenia a skúsenosti remeselníkov pred objednaním",
    "online_booking": "Online rezervácie",
    "online_booking_desc": "Rezervujte si termíny priamo cez kalendár remeselníka bez telefonovania",
    "direct_chat": "Priama komunikácia",
    "direct_chat_desc": "Komunikujte s remeselníkom priamo cez platformu pre dohodnutie detailov",
    "booking_history": "História rezervácií",
    "booking_history_desc": "Sledujte históriu vašich objednávok a uchovávajte kontakty na osvedčených remeselníkov",
    "and": "a",
    
    // Top profile and calendar translations
    "featured_profile": "Zvýraznený profil",
    "get_more_jobs": "Získajte viac zákaziek! Zvýraznite svoj profil v kategórii i výsledkoch vyhľadávania.",
    "profile_is_featured": "Váš profil je zvýraznený a zobrazuje sa na vrchole výsledkov vyhľadávania do",
    "highlight_profile_for": "Zvýrazniť profil na 7 dní (10 €)",
    "processing": "Spracovanie",
    "days": "dní",
    "your_available_days": "Vaše dostupné dni",
    "save_available_days": "Uložiť dostupné dni",
    "craftsman_currently": "Remeselník momentálne nemá stanovené žiadne dostupné termíny.",
    "availability_calendar": "Kalendár dostupnosti",
    "calendar_availability": "Kalendár dostupnosti",
    "account_registration_required": "Pre rezerváciu termínu sa musíte prihlásiť",
    "account_required_message": "Ak chcete kontaktovať tohto remeselníka a rezervovať si termín, musíte byť prihlásený ako zákazník.",
    "login": "Prihlásiť sa",
    "register": "Registrovať sa",
    "your_availability_saved": "Vaša dostupnosť bola úspešne aktualizovaná!",
    "days_available": "Dostupné dni",
    "more": "ďalších",
    "send_message": "Poslať správu",
    "add_new_review": "Pridať nové hodnotenie",
    "edit_review_for": "Upraviť hodnotenie pre",
    "view_all_categories": "Zobraziť všetky kategórie",
    "craftsmen_categories": "Kategórie remeselníkov",
    "categories_of_craftsmen": "Kategórie remeselníkov",
    "craftsman": "Remeselník",
    "kontakt": "Kontakt",
    "profil": "Profil",
    "available_days": "Vaše vybrané dostupné dni"
  },
  cs: {
    // Czech translations
    "welcome": "Vítejte na Majstri.com",
    "platform_description": "Platforma spojující profesionální řemeslníky s lidmi, kteří hledají jejich služby",
    "craftsman": "Jsem řemeslník",
    "customer": "Jsem zákazník",
    "craftsman_desc": "Prezentujte své dovednosti a najděte nové klienty ve vašem okolí",
    "customer_desc": "Najděte spolehlivé řemeslníky pro vaše projekty a vylepšení domácnosti",
    "login": "Přihlášení",
    "register": "Registrovat se",
    "start": "Začít",
    "copyright": "Spojujeme řemeslníky a zákazníky",
    
    // Navbar translations
    "home": "Domů",
    "categories": "Kategorie",
    "find_craftsman": "Najít řemeslníka",
    "jobs": "Zakázky",
    "how_it_works": "Jak to funguje",
    "benefits": "Výhody",
    "messages": "Zprávy",
    "my_profile": "Můj profil",
    "sign_out": "Odhlásit se",
    "sign_in": "Přihlásit se",
    
    // Index page translations
    "professional_craftsmen": "Profesionální řemeslníci na jednom místě",
    "find_best": "Najděte nejlepší",
    "craftsmen": "řemeslníky",
    "platform_connecting": "Platforma, která spojuje profesionální řemeslníky a lidi, kteří potřebují kvalitní služby řemeslníků přímo v České republice.",
    "search_profession": "Hledejte podle profese nebo lokality...",
    "search": "Vyhledat",
    "craftsmen_count": "500+ Řemeslníků",
    "cities_count": "100+ Měst",
    "categories_count": "20+ Kategorií",
    "find_best_craftsmen": "Najděte nejlepší řemeslníky",
    "search_name_craft": "Hledejte podle jména nebo řemesla...",
    "enter_location": "Zadejte lokalitu...",
    "filter_category": "Filtrovat podle kategorie",
    "all_categories": "Všechny kategorie",
    "reset": "Reset",
    "view_all_categories": "Zobrazit všechny kategorie",
    "featured_profiles": "Zvýrazněné profily jsou zobrazeny na vrchu",
    "error_loading": "Nastala chyba při načítání řemeslníků. Zkuste to prosím později.",
    "try_again": "Zkusit znovu",
    "no_craftsmen_found": "Nenašli se žádní řemeslníci podle vašich kritérií. Zkuste upravit vyhledávání.",
    "show_all_craftsmen": "Zobrazit všechny řemeslníky",
    
    // Top profile and calendar translations
    "featured_profile": "Zvýrazněný profil",
    "get_more_jobs": "Získejte více zakázek! Zvýrazněte svůj profil v kategorii i výsledcích vyhledávání.",
    "profile_is_featured": "Váš profil je zvýrazněn a zobrazuje se na vrcholu výsledků vyhledávání do",
    "highlight_profile_for": "Zvýraznit profil na 7 dní (10 €)",
    "processing": "Zpracování",
    "days": "dnů",
    "your_available_days": "Vaše dostupné dny",
    "save_available_days": "Uložit dostupné dny",
    "craftsman_currently": "Řemeslník momentálně nemá stanovené žádné dostupné termíny.",
    "availability_calendar": "Kalendář dostupnosti",
    "calendar_availability": "Kalendář dostupnosti",
    "account_registration_required": "Pro rezervaci termínu se musíte přihlásit",
    "account_required_message": "Pokud chcete kontaktovat tohoto řemeslníka a rezervovat si termín, musíte být přihlášen jako zákazník.",
    "login": "Přihlásit se",
    "register": "Registrovat se",
    "your_availability_saved": "Vaše dostupnost byla úspěšně aktualizována!",
    "days_available": "Dostupné dny",
    "more": "dalších",
    "send_message": "Poslat zprávu",
    "add_new_review": "Přidat nové hodnocení",
    "edit_review_for": "Upravit hodnocení pro",
    "edit_profile": "Upravit profil",
    "portfolio": "Portfolio",
    "reviews": "Hodnocení",
    "calendar": "Kalendář",
    "kontakt": "Kontakt",
    "profil": "Profil",
    "view_all_categories": "Zobrazit všechny kategorie",
    "craftsmen_categories": "Kategorie řemeslníků",
    "categories_of_craftsmen": "Kategorie řemeslníků",
    "craftsman": "Řemeslník",
    "available_days": "Vaše vybrané dostupné dny"
  },
  en: {
    // English translations
    "welcome": "Welcome to Majstri.com",
    "platform_description": "Platform connecting professional craftsmen with people who are looking for their services",
    "craftsman": "I am a craftsman",
    "customer": "I am a customer",
    "craftsman_desc": "Present your skills and find new clients in your area",
    "customer_desc": "Find reliable craftsmen for your projects and home improvements",
    "login": "Login",
    "register": "Register",
    "start": "Start",
    "copyright": "Connecting craftsmen and customers",
    
    // Navbar translations
    "home": "Home",
    "categories": "Categories",
    "find_craftsman": "Find craftsman",
    "jobs": "Jobs",
    "how_it_works": "How it works",
    "benefits": "Benefits",
    "messages": "Messages",
    "my_profile": "My profile",
    "sign_out": "Sign out",
    "sign_in": "Sign in",
    
    // Top profile and calendar translations
    "featured_profile": "Featured Profile",
    "get_more_jobs": "Get more jobs! Highlight your profile in categories and search results.",
    "profile_is_featured": "Your profile is featured and appears at the top of search results until",
    "highlight_profile_for": "Highlight profile for 7 days (€10)",
    "processing": "Processing",
    "days": "days",
    "your_available_days": "Your available days",
    "save_available_days": "Save available days",
    "craftsman_currently": "The craftsman currently has no available appointments set.",
    "availability_calendar": "Availability Calendar",
    "calendar_availability": "Availability Calendar",
    "account_registration_required": "You must be logged in to book an appointment",
    "account_required_message": "If you want to contact this craftsman and book an appointment, you must be logged in as a customer.",
    "login": "Login",
    "register": "Register",
    "your_availability_saved": "Your availability has been successfully updated!",
    "days_available": "Available days",
    "more": "more",
    "send_message": "Send message",
    "add_new_review": "Add new review",
    "edit_review_for": "Edit review for",
    "edit_profile": "Edit profile",
    "portfolio": "Portfolio",
    "reviews": "Reviews",
    "calendar": "Calendar",
    "kontakt": "Contact",
    "profil": "Profile",
    "view_all_categories": "View all categories",
    "craftsmen_categories": "Craftsmen categories",
    "categories_of_craftsmen": "Categories of craftsmen",
    "craftsman": "Craftsman",
    "available_days": "Your selected available days"
  }
};

// Provider component
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // State to store the current language
  const [language, setLanguage] = useState<SupportedLanguage>(() => {
    // Try to get language from localStorage
    const storedLang = localStorage.getItem("language") as SupportedLanguage | null;
    
    // Check browser language
    const browserLang = navigator.language.split("-")[0];
    
    // Return stored language if valid, or check browser language, default to Slovak
    if (storedLang && ["sk", "cs", "en"].includes(storedLang)) {
      return storedLang;
    } else if (["sk", "cs", "en"].includes(browserLang as SupportedLanguage)) {
      return browserLang as SupportedLanguage;
    }
    
    return "sk"; // Default language is Slovak
  });

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // Effect to save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = () => useContext(LanguageContext);
