
import React, { createContext, useContext, useState, useEffect } from "react";

// Define supported languages
export type SupportedLanguage = "sk" | "cs" | "en";

// Define the context type
type LanguageContextType = {
  language: SupportedLanguage;
  setLanguage: (language: SupportedLanguage) => void;
  t: (key: string) => string;
};

// Create the context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: "sk",
  setLanguage: () => {},
  t: (key: string) => key
});

// Translation data
const translations: Record<SupportedLanguage, Record<string, string>> = {
  sk: {
    // Slovak translations
    "welcome": "Vitajte na Majstri.com",
    "platform_description": "Platforma spájajúca profesionálnych remeselníkov s ľuďmi, ktorí hľadajú ich služby",
    "craftsman": "Som remeselník",
    "customer": "Som zákazník",
    "craftsman_desc": "Prezentujte svoje zručnosti a nájdite nových klientov vo vašom okolí",
    "customer_desc": "Nájdite spoľahlivých remeselníkov pre vaše projekty a vylepšenia domácnosti",
    "login": "Prihlásenie",
    "register": "Registrovať sa",
    "start": "Začať",
    "copyright": "Spájame remeselníkov a zákazníkov",
    
    // Navbar translations
    "home": "Domov",
    "categories": "Kategórie",
    "find_craftsman": "Nájsť remeselníka",
    "jobs": "Zákazky",
    "how_it_works": "Ako to funguje",
    "benefits": "Výhody",
    "messages": "Správy",
    "my_profile": "Môj profil",
    "sign_out": "Odhlásiť sa",
    "sign_in": "Prihlásiť sa",
    
    // Index page translations
    "professional_craftsmen": "Profesionálni remeselníci na jednom mieste",
    "find_best": "Nájdite najlepších",
    "craftsmen": "remeselníkov",
    "platform_connecting": "Platforma, ktorá spája profesionálnych remeselníkov a ľudí, ktorí potrebujú kvalitné služby remeselníkov priamo na Slovensku.",
    "search_profession": "Hľadajte podľa profesie alebo lokality...",
    "search": "Vyhľadať",
    "craftsmen_count": "500+ Remeselníkov",
    "cities_count": "100+ Miest",
    "categories_count": "20+ Kategórií",
    "find_best_craftsmen": "Nájdite najlepších remeselníkov",
    "search_name_craft": "Hľadajte podľa mena alebo remesla...",
    "enter_location": "Zadajte lokalitu...",
    "filter_category": "Filter podľa kategórie",
    "all_categories": "Všetky kategórie",
    "reset": "Reset",
    "view_all_categories": "Zobraziť všetky kategórie",
    "featured_profiles": "Zvýraznené profily sú zobrazené na vrchu",
    "error_loading": "Nastala chyba pri načítaní remeselníkov. Skúste to prosím neskôr.",
    "try_again": "Skúsiť znova",
    "no_craftsmen_found": "Nenašli sa žiadni remeselníci podľa vašich kritérií. Skúste upraviť vyhľadávanie.",
    "show_all_craftsmen": "Zobraziť všetkých remeselníkov",
    
    // About page
    "about_us": "O nás",
    
    // Footer translations
    "for_craftsmen": "Pre remeselníkov",
    "registration": "Registrácia",
    "pricing": "Cenník služieb",
    "registration_benefits": "Výhody registrácie",
    "for_customers": "Pre zákazníkov",
    "find_craftsmen": "Vyhľadať remeselníkov",
    "service_categories": "Kategórie služieb",
    "how_it_works_footer": "Ako to funguje",
    "reviews_ratings": "Hodnotenia a recenzie",
    "company": "Spoločnosť",
    "about_us_footer": "O nás",
    "contact": "Kontakt",
    "privacy": "Ochrana súkromia",
    "terms": "Podmienky používania",
    "all_rights_reserved": "Všetky práva vyhradené",
    
    // Profile translations
    "edit_profile": "Upraviť profil",
    "portfolio": "Portfólio",
    "reviews": "Hodnotenia",
    "calendar": "Kalendár",
    "contact_us": "Kontaktujte nás",
    "loading": "Načítavam...",
    "set_availability_profile": "Nastavte svoju dostupnosť v sekcii \"Kalendár dostupnosti\" vyššie na tejto stránke.",
    "contact_message": "Tu môžete vidieť dostupnosť remeselníka a kontaktovať ho prostredníctvom správy.",
    "send_message": "Poslať správu",
    "book_appointment": "Rezervácia termínu",
    "send_message_tab": "Poslať správu",
    "select_date": "1. Vyberte dátum",
    "select_time": "2. Vyberte čas",
    "request_details": "3. Detaily požiadavky",
    "job_description": "Popis práce*",
    "job_description_placeholder": "Opíšte, akú prácu potrebujete vykonať...",
    "address": "Adresa*",
    "address_placeholder": "Zadajte adresu, kde sa má práca vykonať",
    "estimated_price": "Predpokladaná cena",
    "estimated_price_placeholder": "Zadajte predpokladanú cenu",
    "add_photo": "Pridať fotografiu (voliteľné)",
    "upload_image": "Nahrať obrázok",
    "submit_request": "Odoslať požiadavku",
    "sending": "Odosielam...",
    "hourly_rate": "Hodinová sadzba",
    "loading_dates": "Načítavam dostupné termíny...",
    "craftsman_available": "Remeselník je dostupný v označené dni",
    "no_time_slots": "Žiadne dostupné termíny",
    "contact_craftsman_message": "Poslať správu remeselníkovi",
    "contact_message_desc": "Kliknite na tlačidlo nižšie pre kontaktovanie remeselníka priamo cez správy.",
    "go_to_messages": "Prejsť na správy",
    
    // Messages
    "messages_title": "Správy",
    "login_required": "Pre prístup k správam sa musíte prihlásiť",
    
    // Error messages
    "profile_access_error": "Chyba prístupu k profilu",
    "profile_access_message": "Nemáte oprávnenie na zobrazenie tohto profilu. Toto môže byť spôsobené nastaveniami Row Level Security (RLS) v databáze.",
    "rls_block_message": "Hoci ste prihlásený ako vlastník profilu, RLS pravidlá môžu blokovať prístup. Skúste sa odhlásiť a znova prihlásiť.",
    "create_profile_again": "Vytvoriť profil znova",
    "database_error": "Nastala chyba pripojenia k databáze",
    "database_error_message": "Nepodarilo sa spojiť s databázou. Skúste stránku obnoviť alebo to skúste znova neskôr.",
    "unexpected_error": "Nastala neočakávaná chyba",
    "try_again_later": "Skúste stránku obnoviť alebo to skúste znova neskôr.",
    "refresh_page": "Obnoviť stránku",
    
    // Benefits page
    "benefits_title": "Výhody pre remeselníkov",
    "benefit_1_title": "Nové obchodné príležitosti",
    "benefit_1_desc": "Získajte prístup k novým zákazníkom, ktorí aktívne hľadajú služby ako sú tie vaše.",
    "benefit_2_title": "Online prítomnosť",
    "benefit_2_desc": "Vytvorte si profesionálny profil, ktorý zvýši vašu viditeľnosť a dôveryhodnosť.",
    "benefit_3_title": "Flexibilný kalendár",
    "benefit_3_desc": "Spravujte svoju dostupnosť a prijímajte rezervácie, ktoré vyhovujú vášmu harmonogramu.",
    "benefit_4_title": "Hodnotenia a recenzie",
    "benefit_4_desc": "Budujte svoju reputáciu prostredníctvom spätnej väzby od spokojných zákazníkov.",
    "register_now": "Zaregistrujte sa teraz",
    "learn_more": "Dozvedieť sa viac",
    
    // Pricing page
    "pricing_title": "Cenník služieb",
    "basic_plan": "Základný plán",
    "basic_price": "0 € / mesiac",
    "basic_description": "Ideálne pre začínajúcich remeselníkov alebo tých, ktorí chcú vyskúšať platformu.",
    "premium_plan": "Premium plán",
    "premium_price": "19,99 € / mesiac",
    "premium_description": "Pre profesionálnych remeselníkov, ktorí chcú maximalizovať svoj potenciál.",
    "profile_feature": "Profesionálny profil",
    "portfolio_feature": "Fotografie portfólia",
    "reviews_feature": "Hodnotenia a recenzie",
    "basic_requests": "Obmedzené žiadosti",
    "premium_requests": "Neobmedzené žiadosti",
    "priority_listing": "Prioritné zobrazenie vo vyhľadávaní",
    "analytics_feature": "Analytika a reporty",
    "premium_support": "Prioritná podpora",
    "featured_profile": "Zvýraznený profil",
    "choose_plan": "Vybrať plán",
    "current_plan": "Váš aktuálny plán",
    
    // How it works page
    "how_it_works_title": "Ako to funguje",
    "choose_category": "Vyberte kategóriu",
    "choose_category_desc": "Prechádzajte kategóriami a vyhľadajte typ remeselníka, ktorého potrebujete.",
    "view_profiles": "Prehliadajte profily",
    "view_profiles_desc": "Prehliadajte si detailné profily, hodnotenia a portfóliá remeselníkov.",
    "contact_craftsman_step": "Kontaktujte remeselníka",
    "contact_craftsman_step_desc": "Kontaktujte vybraného remeselníka priamo cez našu platformu.",
    "book_appointment_step": "Rezervujte si termín",
    "book_appointment_step_desc": "Vyberte si termín, ktorý vám vyhovuje, z dostupného kalendára remeselníka.",
    "rate_after_completion": "Ohodnoťte službu",
    "rate_after_completion_desc": "Po dokončení práce zanechajte hodnotenie a pomôžte ostatným zákazníkom.",
    
    "register_create_profile": "Vytvorte si profil",
    "register_create_profile_desc": "Zaregistrujte sa a vytvorte si profesionálny profil, ktorý ukáže vaše zručnosti.",
    "set_availability": "Nastavte dostupnosť",
    "set_availability_desc": "Nastavte svoj kalendár, aby zákazníci videli, kedy ste k dispozícii.",
    "communicate_with_customers": "Komunikujte so zákazníkmi",
    "communicate_with_customers_desc": "Odpovedajte na správy a požiadavky zákazníkov prostredníctvom platformy.",
    "gather_reviews": "Zbierajte hodnotenia",
    "gather_reviews_desc": "Získajte pozitívne hodnotenia a budujte svou online reputaciu.",
    "highlight_profile": "Zvýraznite svoj profil",
    "highlight_profile_desc": "Využite možnosti prémiových funkcií na zvýraznenie vášho profilu vo vyhľadávaní.",
    "more_questions": "Máte ďalšie otázky o tom, ako naša platforma funguje?",
    
    // Categories
    "carpentry": "Stolár",
    "electrician": "Elektrikár",
    "mason": "Murár",
    "plumber": "Inštalatér",
    "painter": "Maliar",
    "flooring": "Podlahár",
    "tinsmiths": "Klampiar",
    "locksmith": "Zámočník",
    "carpenter": "Tesár",
    "gardener": "Záhradník",
    "heating": "Kúrenár",
    "glazier": "Sklenár",
    
    // Terms of service page
    "terms_of_service": "Podmienky používania",
    "basic_information": "Základné informácie",
    "terms_intro": "Tieto podmienky používania upravujú vaše používanie služieb poskytovaných na Majstri.com. Ak máte akékoľvek otázky, kontaktujte nás na",
    "registration_age": "Vekové obmedzenie",
    "registration_age_desc": "Na registráciu a používanie našej platformy musíte mať najmenej 18 rokov alebo dovŕšiť vek plnoletosti vo vašej krajine.",
    "user_types": "Typy používateľov",
    "platform_user_types": "Naša platforma rozlišuje dva hlavné typy používateľov",
    "user_content": "Používateľský obsah",
    "user_content_desc": "Používatelia sú zodpovední za všetok obsah, ktorý nahrajú alebo zdieľajú na platforme, vrátane fotografií, recenzií a profilových informácií.",
    "ratings_reviews": "Hodnotenia a recenzie",
    "ratings_reviews_desc": "Zákazníci môžu zanechávať hodnotenia a recenzie na základe ich skúseností. Všetky recenzie musia byť úprimné a založené na skutočných skúsenostiach.",
    "bookings_communication": "Rezervácie a komunikácia",
    "bookings_communication_desc": "Všetky rezervácie a komunikácia by mali prebiehať prostredníctvom našej platformy, aby sme mohli zabezpečiť kvalitu služieb a riešiť prípadné problémy.",
    "responsibility": "Zodpovednosť",
    "responsibility_desc": "Platforma slúži iba ako sprostredkovateľ medzi remeselníkmi a zákazníkmi. Nenesieme zodpovednosť za kvalitu vykonaných prác ani za prípadné škody.",
    "payments": "Platby",
    "payments_desc": "Platby za služby sú dohodnuté priamo medzi remeselníkom a zákazníkom. Platforma môže účtovať poplatky za určité prémiové funkcie alebo služby.",
    "account_restrictions": "Obmedzenia účtu",
    "account_restrictions_desc": "Vyhradzujeme si právo obmedziť, pozastaviť alebo ukončiť účty, ktoré porušujú tieto podmienky alebo sú zapojené do podvodných aktivít.",
    "promotion_outside": "Propagácia mimo platformy",
    "promotion_outside_desc": "Remeselníci nesmú presmerovať zákazníkov mimo platformy s cieľom obísť poplatky alebo pravidlá platformy.",
    "data_protection": "Ochrana údajov",
    "data_protection_desc": "Spracúvame osobné údaje v súlade s našimi zásadami ochrany osobných údajov a príslušnými právnymi predpismi.",
    "analytics_cookies": "Analytika a cookies",
    "analytics_cookies_desc": "Používame cookies a analytické nástroje na zlepšenie našich služieb a zlepšenie používateľského zážitku.",
    "final_provisions": "Záverečné ustanovenia",
    "final_provisions_desc": "Vyhradzujeme si právo kedykoľvek zmeniť tieto podmienky používania. Aktuálnu verziu podmienok nájdete vždy na našom webe.",
    
    // New categories
    "drywaller": "Sádrokartonista",
    "tiler": "Obkladač",
    "wallpaper": "Tapetár",
    "chimney": "Kominár",
    "tv_tech": "TV/SAT Technik",
    "ac_tech": "Chladiar/Klimatizér",
    "furniture": "Montér nábytku",
    "auto": "Autoelektrikár / Automechanik",
    "metalwork": "Kovovýroba",
    "appliance": "Servis domácich spotrebičov",
    "it": "IT technik",
    "welder": "Zvárač",
    "cleaning": "Upratovacie služby",
    "woodcarving": "Drevorezbár / Umelecký stolár",
    "garden_architect": "Záhradný architekt",
    "window": "Okenár / Montáž okien a dverí",
    "solar": "Montér solárnych panelov",
    "scaffolder": "Lešenár",
    "masseur": "Masér / Masérka",
    "cosmetician": "Kozmetička",
    "nail": "Nechtový dizajnér / Manikérka",
    "pedicure": "Pedikér / Pedikérka",
    "makeup": "Vizážistka / Make-up artist",
    "hairdresser": "Kaderník / Kaderníčka",
    "barber": "Barber",
    "lash": "Lash & Brow artist",
    "tattoo": "Tetovanie / Permanentný make-up",
    "wellness": "Wellness terapeut",
    
    // Profile sections
    "profile_not_found": "Profil nebol nájdený",
    "create_profile": "Vytvoriť profil",
    "profile_creation_error": "Chyba pri vytváraní profilu",
    "profile_completion": "Dokončenie profilu",
    "user_type_question": "Aký typ používateľa ste?",
    "years_experience": "Roky skúseností",
    "specialization": "Špecializácia",
    "about_me": "O mne",
    "projects": "Projekty",
    "no_projects": "Zatiaľ nie sú pridané žiadne projekty",
    "add_project": "Pridať projekt",
    "portfolio_images": "Obrázky portfólia",
    "upload_portfolio": "Nahrať obrázky portfólia",
    "add_review": "Pridať hodnotenie",
    "select_craftsman": "Vyberte remeselníka",
    "write_review": "Napíšte recenziu",
    "rating": "Hodnotenie",
    "comment": "Komentár",
    "submit_review": "Odoslať hodnotenie",
    "edit_review": "Upraviť hodnotenie",
    "delete_review": "Vymazať hodnotenie",
    "reply": "Odpovedať",
    "edit_reply": "Upraviť odpoveď",
    "delete_reply": "Vymazať odpoveď",
    "save_changes": "Uložiť zmeny",
    "cancel": "Zrušiť",
    "availability_settings": "Nastavenia dostupnosti",
    "availability_calendar": "Kalendár dostupnosti",
    "set_time_slots": "Nastaviť časové sloty",
    "unavailable": "Nedostupný",
    "available_all_day": "Dostupný celý deň",
    "custom_hours": "Vlastné hodiny",
    "start_time": "Čas začiatku",
    "end_time": "Čas konca",
    "update_availability": "Aktualizovať dostupnosť",
    "availability_updated": "Dostupnosť bola aktualizovaná",
    "error_updating": "Chyba pri aktualizácii",
    
    // Reviews and profile sections
    "write_comment_placeholder": "Napíšte váš názor na prácu remeselníka...",
    "anonymous_customer": "Anonymný zákazník",
    "craftsman_response": "Odpoveď remeselníka",
    "no_reviews": "Zatiaľ nie sú žiadne hodnotenia",
    "be_first": "Buďte prvý, kto ohodnotí tohto remeselníka",
    "based_on": "Na základe",
    "ratings": "hodnotení",
    "personal_info": "Osobné informácie",
    "business_info": "Informácie o podnikaní",
    "location_label": "Lokalita",
    "phone_label": "Telefón",
    "email_label": "E-mail",
    "save_profile": "Uložiť profil",
    "saving": "Ukladám...",
    "profile_updated": "Profil bol aktualizovaný",
    "error_saving": "Chyba pri ukladaní profilu",
    
    // Chat and messages
    "conversation_with": "Konverzácia s",
    "new_message": "Nová správa",
    "select_recipient": "Vyberte príjemcu",
    "message_placeholder": "Napíšte správu...",
    "send": "Odoslať",
    "no_conversations": "Zatiaľ nemáte žiadne konverzácie",
    "start_conversation": "Začnite konverzáciu s remeselníkom alebo zákazníkom",
    "no_messages": "Zatiaľ nie sú žiadne správy",
    "type_message": "Napíšte správu pre začatie konverzácie",
    "message_sent": "Správa odoslaná",
    "error_sending": "Chyba pri odosielaní správy",
    "delete_conversation": "Vymazať konverzáciu",
    "archive_conversation": "Archivovať konverzáciu",
    "confirm_delete": "Naozaj chcete vymazať túto konverzáciu?",
    "yes_delete": "Áno, vymazať",
    
    // Privacy page translations
    "privacy_policy": "Zásady ochrany osobných údajov", 
    "last_updated": "Posledná aktualizácia",
    "may": "máj",
    "privacy_intro": "V týchto zásadách ochrany osobných údajov vám vysvetľujeme, ako zhromažďujeme, používame a chránime vaše osobné údaje pri používaní našej platformy.",
    "who_processes_data": "Kto spracúva vaše údaje",
    "data_controller_desc": "Správcom osobných údajov je prevádzkovateľ služby Majstri.com. Pre otázky ohľadom ochrany osobných údajov nás kontaktujte na",
    "what_data_processed": "Aké údaje spracúvame",
    "registration_data_desc": "Pri registrácii a používaní našej platformy zbierame nasledujúce údaje",
    "full_name": "Celé meno",
    "email_address": "E-mailová adresa",
    "phone_number": "Telefónne číslo",
    "city_of_residence": "Mesto bydliska",
    "data_purpose_desc": "Tieto údaje sú nevyhnutné na poskytovanie našich služieb, umožnenie komunikácie medzi používateľmi a zabezpečenie bezpečnosti na platforme.",
    "data_purpose": "Účel spracovania údajov",
    "data_processing_purposes": "Vaše osobné údaje spracúvame na nasledujúce účely",
    "registration_account": "Registrácia a správa účtu",
    "profile_creation": "Vytvorenie a prezentácia profilu",
    "contact_facilitation": "Uľahčenie kontaktu medzi remeselníkmi a zákazníkmi",
    "system_messages": "Zasielanie systémových správ",
    "platform_updates": "Informovanie o novinkách a aktualizáciách platformy",
    "data_access": "Prístup k vašim údajom",
    "data_access_desc": "K vašim údajom majú prístup len oprávnení zamestnanci a spolupracovníci, ktorí potrebujú tieto údaje na plnenie svojich pracovných povinností. Tretiím stranám poskytujeme údaje len v rozsahu nevyhnutnom na poskytovanie našich služieb alebo ak to vyžaduje zákon.",
    "data_retention": "Doba uchovávania údajov",
    "data_retention_desc": "Vaše osobné údaje uchovávame po dobu aktívneho užívania vašeho účtu a ešte po dobu 2 rokov po poslednej aktivite. Po uplynutí tejto doby sú údaje anonymizovené alebo vymazané.",
    "cookies_usage": "Používanie cookies",
    "cookies_usage_desc": "Naša webová stránka používa cookies na zlepšenie používateľského zážitku, analýzu návštevnosti a poskytovanie personalizovaných funkcií. Používaním našich služieb súhlasíte s používaním cookies v súlade s našimi zásadami.",
    "data_transfer": "Prenos údajov do zahraničia",
    "data_transfer_desc": "Vaše osobné údaje môžu byť prenášané a uchovávané na serveroch mimo vašej krajiny, ale vždy v súlade s príslušnými zákonmi o ochrane osobných údajov."
  },
  cs: {
    // Czech translations
    "welcome": "Vítejte na Majstri.com",
    "platform_description": "Platforma spojující profesionální řemeslníky s lidmi, kteří hledají jejich služby",
    "craftsman": "Jsem řemeslník",
    "customer": "Jsem zákazník",
    "craftsman_desc": "Prezentujte své dovednosti a najděte nové klienty ve vašem okolí",
    "customer_desc": "Najděte spolehlivé řemeslníky pro vaše projekty a vylepšení domácnosti",
    "login": "Přihlášení",
    "register": "Registrovat se",
    "start": "Začít",
    "copyright": "Spojujeme řemeslníky a zákazníky",
    
    // Navbar translations
    "home": "Domů",
    "categories": "Kategorie",
    "find_craftsman": "Najít řemeslníka",
    "jobs": "Zakázky",
    "how_it_works": "Jak to funguje",
    "benefits": "Výhody",
    "messages": "Zprávy",
    "my_profile": "Můj profil",
    "sign_out": "Odhlásit se",
    "sign_in": "Přihlásit se",
    
    // Index page translations
    "professional_craftsmen": "Profesionální řemeslníci na jednom místě",
    "find_best": "Najděte nejlepší",
    "craftsmen": "řemeslníky",
    "platform_connecting": "Platforma, která spojuje profesionální řemeslníky a lidi, kteří potřebují kvalitní služby řemeslníků přímo v Česku.",
    "search_profession": "Hledejte podle profese nebo lokality...",
    "search": "Vyhledat",
    "craftsmen_count": "500+ Řemeslníků",
    "cities_count": "100+ Měst",
    "categories_count": "20+ Kategorií",
    "find_best_craftsmen": "Najděte nejlepší řemeslníky",
    "search_name_craft": "Hledejte podle jména nebo řemesla...",
    "enter_location": "Zadejte lokalitu...",
    "filter_category": "Filtrovat podle kategorie",
    "all_categories": "Všechny kategorie",
    "reset": "Reset",
    "view_all_categories": "Zobrazit všechny kategorie",
    "featured_profiles": "Zvýrazněné profily jsou zobrazeny nahoře",
    "error_loading": "Nastala chyba při načítání řemeslníků. Zkuste to prosím později.",
    "try_again": "Zkusit znovu",
    "no_craftsmen_found": "Nenašli se žádní řemeslníci podle vašich kritérií. Zkuste upravit vyhledávání.",
    "show_all_craftsmen": "Zobrazit všechny řemeslníky",
    
    // About page
    "about_us": "O nás",
    
    // Footer translations
    "for_craftsmen": "Pro řemeslníky",
    "registration": "Registrace",
    "pricing": "Ceník služeb",
    "registration_benefits": "Výhody registrace",
    "for_customers": "Pro zákazníky",
    "find_craftsmen": "Vyhledat řemeslníky",
    "service_categories": "Kategorie služeb",
    "how_it_works_footer": "Jak to funguje",
    "reviews_ratings": "Hodnocení a recenze",
    "company": "Společnost",
    "about_us_footer": "O nás",
    "contact": "Kontakt",
    "privacy": "Ochrana soukromí",
    "terms": "Podmínky používání",
    "all_rights_reserved": "Všechna práva vyhrazena",
    
    // Profile translations
    "edit_profile": "Upravit profil",
    "portfolio": "Portfolio",
    "reviews": "Hodnocení",
    "calendar": "Kalendář",
    "contact_us": "Kontaktujte nás",
    "loading": "Načítám...",
    "set_availability": "Nastavte svou dostupnost v sekci \"Kalendář dostupnosti\" výše na této stránce.",
    "contact_message": "Zde můžete vidět dostupnost řemeslníka a kontaktovat ho prostřednictvím zprávy.",
    "send_message": "Poslat zprávu",
    "book_appointment": "Rezervace termínu",
    "send_message_tab": "Poslat zprávu",
    "select_date": "1. Vyberte datum",
    "select_time": "2. Vyberte čas",
    "request_details": "3. Detaily požadavku",
    "job_description": "Popis práce*",
    "job_description_placeholder": "Popište, jakou práci potřebujete vykonat...",
    "address": "Adresa*",
    "address_placeholder": "Zadejte adresu, kde se má práce vykonat",
    "estimated_price": "Předpokládaná cena",
    "estimated_price_placeholder": "Zadejte předpokládanou cenu",
    "add_photo": "Přidat fotografii (volitelné)",
    "upload_image": "Nahrát obrázek",
    "submit_request": "Odeslat požadavek",
    "sending": "Odesílám...",
    "hourly_rate": "Hodinová sazba",
    "loading_dates": "Načítám dostupné termíny...",
    "craftsman_available": "Řemeslník je dostupný v označené dny",
    "no_time_slots": "Žádné dostupné termíny",
    "contact_craftsman_message": "Poslat zprávu řemeslníkovi",
    "contact_message_desc": "Klikněte na tlačítko níže pro kontaktování řemeslníka přímo přes zprávy.",
    "go_to_messages": "Přejít na zprávy",
    
    // Messages
    "messages_title": "Zprávy",
    "login_required": "Pro přístup ke zprávám se musíte přihlásit",
    
    // Error messages
    "profile_access_error": "Chyba přístupu k profilu",
    "profile_access_message": "Nemáte oprávnění k zobrazení tohoto profilu. Toto může být způsobeno nastavením Row Level Security (RLS) v databázi.",
    "rls_block_message": "Přestože jste přihlášen jako vlastník profilu, RLS pravidla mohou blokovat přístup. Zkuste se odhlásit a znovu přihlásit.",
    "create_profile_again": "Vytvořit profil znovu",
    "database_error": "Nastala chyba připojení k databázi",
    "database_error_message": "Nepodařilo se spojit s databází. Zkuste stránku obnovit nebo to zkuste znovu později.",
    "unexpected_error": "Nastala neočekávaná chyba",
    "try_again_later": "Zkuste stránku obnovit nebo to zkuste znovu později.",
    "refresh_page": "Obnovit stránku",
    
    // Benefits page
    "benefits_title": "Výhody pro řemeslníky",
    "benefit_1_title": "Nové obchodní příležitosti",
    "benefit_1_desc": "Získejte přístup k novým zákazníkům, kteří aktivně hledají služby jako jsou ty vaše.",
    "benefit_2_title": "Online přítomnost",
    "benefit_2_desc": "Vytvořte si profesionální profil, který zvýší vaši viditelnost a důvěryhodnost.",
    "benefit_3_title": "Flexibilní kalendář",
    "benefit_3_desc": "Spravujte svou dostupnost a přijímejte rezervace, které vyhovují vašemu harmonogramu.",
    "benefit_4_title": "Hodnocení a recenze",
    "benefit_4_desc": "Budujte svou reputaci prostřednictvím zpětné vazby od spokojených zákazníků.",
    "register_now": "Zaregistrujte se nyní",
    "learn_more": "Dozvědět se více",
    
    // Pricing page
    "pricing_title": "Ceník služeb",
    "basic_plan": "Základní plán",
    "basic_price": "0 € / měsíc",
    "basic_description": "Ideální pro začínající řemeslníky nebo ty, kteří chtějí vyzkoušet platformu.",
    "premium_plan": "Premium plán",
    "premium_price": "19,99 € / měsíc",
    "premium_description": "Pro profesionální řemeslníky, kteří chtějí maximalizovat svůj potenciál.",
    "profile_feature": "Profesionální profil",
    "portfolio_feature": "Fotografie portfolia",
    "reviews_feature": "Hodnocení a recenze",
    "basic_requests": "Omezené žádosti",
    "premium_requests": "Neomezené žádosti",
    "priority_listing": "Prioritní zobrazení ve vyhledávání",
    "analytics_feature": "Analytika a reporty",
    "premium_support": "Prioritní podpora",
    "featured_profile": "Zvýrazněný profil",
    "choose_plan": "Vybrat plán",
    "current_plan": "Váš aktuální plán",
    
    // How it works page
    "how_it_works_title": "Jak to funguje",
    "for_craftsmen_title": "Pro řemeslníky",
    "step_1_craftsman": "1. Vytvořte si profil",
    "step_1_craftsman_desc": "Vytvořte si bezplatný profil a ukažte své dovednosti a portfolio.",
    "step_2_craftsman": "2. Nastavte svou dostupnost",
    "step_2_craftsman_desc": "Nastavte svůj kalendář, aby zákazníci věděli, kdy jste k dispozici.",
    "step_3_craftsman": "3. Získejte zakázky",
    "step_3_craftsman_desc": "Přijímejte žádosti a komunikujte se zákazníky.",
    "for_customers_title": "Pro zákazníky",
    "step_1_customer": "1. Vyhledejte řemeslníka",
    "step_1_customer_desc": "Prohlížejte si profily řemeslníků a hodnocení od jiných zákazníků.",
    "step_2_customer": "2. Kontaktujte řemeslníka",
    "step_2_customer_desc": "Pošlete zprávu nebo si zarezervujte termín přímo přes platformu.",
    "step_3_customer": "3. Získejte kvalitní službu",
    "step_3_customer_desc": "Užijte si profesionální služby a poté zanechte hodnocení.",
    
    // Privacy page translations
    "privacy_policy": "Zásady ochrany osobních údajů",
    "last_updated": "Poslední aktualizace",
    "may": "květen",
    "privacy_intro": "V těchto zásadách ochrany osobních údajů vám vysvětlujeme, jak shromažďujeme, používáme a chráníme vaše osobní údaje při používání naší platformy.",
    "who_processes_data": "Kdo zpracovává vaše údaje",
    "data_controller_desc": "Správcem osobních údajů je provozovatel služby Majstri.com. Pro otázky ohledně ochrany osobních údajů nás kontaktujte na",
    "what_data_processed": "Jaké údaje zpracováváme",
    "registration_data_desc": "Při registraci a používání naší platformy sbíráme následující údaje",
    "full_name": "Celé jméno",
    "email_address": "E-mailová adresa",
    "phone_number": "Telefonní číslo",
    "city_of_residence": "Město bydliště",
    "data_purpose_desc": "Tyto údaje jsou nezbytné pro poskytování našich služeb, umožnění komunikace mezi uživateli a zajištění bezpečnosti na platformě.",
    "data_purpose": "Účel zpracování údajů",
    "data_processing_purposes": "Vaše osobní údaje zpracováváme k následujícím účelům",
    "registration_account": "Registrace a správa účtu",
    "profile_creation": "Vytvoření a prezentace profilu",
    "contact_facilitation": "Usnadnění kontaktu mezi řemeslníky a zákazníky",
    "system_messages": "Zasílání systémových zpráv",
    "platform_updates": "Informování o novinkách a aktualizacích platformy",
    "data_access": "Přístup k vašim údajům",
    "data_access_desc": "K vašim údajům mají přístup pouze oprávnění zaměstnanci a spolupracovníci, kteří potřebují tyto údaje k plnění svých pracovních povinností. Třetím stranám poskytujeme údaje pouze v rozsahu nezbytném pro poskytování našich služeb nebo pokud to vyžaduje zákon.",
    "data_retention": "Doba uchovávání údajů",
    "data_retention_desc": "Vaše osobní údaje uchováváme po dobu aktivního užívání vašeho účtu a ještě po dobu 2 let po poslední aktivitě. Po uplynutí této doby jsou údaje anonymizovány nebo smazány.",
    "cookies_usage": "Používání cookies",
    "cookies_usage_desc": "Naše webová stránka používá cookies pro zlepšení uživatelského zážitku, analýzu návštěvnosti a poskytování personalizovaných funkcí. Používáním našich služeb souhlasíte s používáním cookies v souladu s našimi zásadami.",
    "data_transfer": "Přenos údajů do zahraničí",
    "data_transfer_desc": "Vaše osobní údaje mohou být přenášeny a uchovávány na serverech mimo vaši zemi, ale vždy v souladu s příslušnými zákony o ochraně osobních údajů.",
    
    // Terms of service page
    "terms_of_service": "Podmínky používání",
    "basic_information": "Základní informace",
    "terms_intro": "Tyto podmínky používání upravují vaše používání služeb poskytovaných na Majstri.com. Pokud máte jakékoliv otázky, kontaktujte nás na",
    "registration_age": "Věkové omezení",
    "registration_age_desc": "Pro registraci a používání naší platformy musíte mít nejméně 18 let nebo dosáhnout věku plnoletosti ve vaší zemi.",
    "user_types": "Typy uživatelů",
    "platform_user_types": "Naše platforma rozlišuje dva hlavní typy uživatelů",
    "user_content": "Uživatelský obsah",
    "user_content_desc": "Uživatelé jsou zodpovědní za veškerý obsah, který nahrají nebo sdílejí na platformě, včetně fotografií, recenzí a profilových informací.",
    "ratings_reviews": "Hodnocení a recenze",
    "ratings_reviews_desc": "Zákazníci mohou zanechávat hodnocení a recenze na základě jejich zkušeností. Všechny recenze musí být upřímné a založené na skutečných zkušenostech.",
    "bookings_communication": "Rezervace a komunikace",
    "bookings_communication_desc": "Všechny rezervace a komunikace by měly probíhat prostřednictvím naší platformy, abychom mohli zajistit kvalitu služeb a řešit případné problémy.",
    "responsibility": "Zodpovědnost",
    "responsibility_desc": "Platforma slouží pouze jako zprostředkovatel mezi řemeslníky a zákazníky. Neneseme odpovědnost za kvalitu provedených prací ani za případné škody.",
    "payments": "Platby",
    "payments_desc": "Platby za služby jsou dohodnuty přímo mezi řemeslníkem a zákazníkem. Platforma může účtovat poplatky za určité prémiové funkce nebo služby.",
    "account_restrictions": "Omezení účtu",
    "account_restrictions_desc": "Vyhrazujeme si právo omezit, pozastavit nebo ukončit účty, které porušují tyto podmínky nebo jsou zapojeny do podvodných aktivit.",
    "promotion_outside": "Propagace mimo platformu",
    "promotion_outside_desc": "Řemeslníci nesmí přesměrovat zákazníky mimo platformu s cílem obejít poplatky nebo pravidla platformy.",
    "data_protection": "Ochrana údajů",
    "data_protection_desc": "Zpracováváme osobní údaje v souladu s našimi zásadami ochrany osobních údajů a příslušnými právními předpisy.",
    "analytics_cookies": "Analytika a cookies",
    "analytics_cookies_desc": "Používáme cookies a analytické nástroje pro zlepšení našich služeb a zlepšení uživatelského zážitku.",
    "final_provisions": "Závěrečná ustanovení",
    "final_provisions_desc": "Vyhrazujeme si právo kdykoliv změnit tyto podmínky používání. Aktuální verzi podmínek najdete vždy na našem webu."
  },
  en: {
    // English translations
    "welcome": "Welcome to Majstri.com",
    "platform_description": "A platform connecting professional craftsmen with people looking for their services",
    "craftsman": "I am a craftsman",
    "customer": "I am a customer",
    "craftsman_desc": "Showcase your skills and find new clients in your area",
    "customer_desc": "Find reliable craftsmen for your projects and home improvements",
    "login": "Login",
    "register": "Register",
    "start": "Get Started",
    "copyright": "Connecting craftsmen and customers",
    
    // Navbar translations
    "home": "Home",
    "categories": "Categories",
    "find_craftsman": "Find Craftsman",
    "jobs": "Jobs",
    "how_it_works": "How It Works",
    "benefits": "Benefits",
    "messages": "Messages",
    "my_profile": "My Profile",
    "sign_out": "Sign Out",
    "sign_in": "Sign In",
    
    // Index page translations
    "professional_craftsmen": "Professional craftsmen in one place",
    "find_best": "Find the best",
    "craftsmen": "craftsmen",
    "platform_connecting": "A platform that connects professional craftsmen and people who need quality craftsman services.",
    "search_profession": "Search by profession or location...",
    "search": "Search",
    "craftsmen_count": "500+ Craftsmen",
    "cities_count": "100+ Cities",
    "categories_count": "20+ Categories",
    "find_best_craftsmen": "Find the best craftsmen",
    "search_name_craft": "Search by name or craft...",
    "enter_location": "Enter location...",
    "filter_category": "Filter by category",
    "all_categories": "All categories",
    "reset": "Reset",
    "view_all_categories": "View all categories",
    "featured_profiles": "Featured profiles are displayed at the top",
    "error_loading": "An error occurred while loading craftsmen. Please try again later.",
    "try_again": "Try again",
    "no_craftsmen_found": "No craftsmen were found matching your criteria. Try adjusting your search.",
    "show_all_craftsmen": "Show all craftsmen",
    
    // About page
    "about_us": "About Us",
    
    // Footer translations
    "for_craftsmen": "For Craftsmen",
    "registration": "Registration",
    "pricing": "Service Pricing",
    "registration_benefits": "Registration Benefits",
    "for_customers": "For Customers",
    "find_craftsmen": "Find Craftsmen",
    "service_categories": "Service Categories",
    "how_it_works_footer": "How It Works",
    "reviews_ratings": "Reviews and Ratings",
    "company": "Company",
    "about_us_footer": "About Us",
    "contact": "Contact",
    "privacy": "Privacy Policy",
    "terms": "Terms of Service",
    "all_rights_reserved": "All rights reserved",
    
    // Profile translations
    "edit_profile": "Edit Profile",
    "portfolio": "Portfolio",
    "reviews": "Reviews",
    "calendar": "Calendar",
    "contact_us": "Contact Us",
    "loading": "Loading...",
    "set_availability_profile": "Set your availability in the \"Calendar Availability\" section above on this page.",
    "contact_message": "Here you can see the availability of the craftsman and contact them through a message.",
    "send_message": "Send Message",
    "book_appointment": "Book Appointment",
    "send_message_tab": "Send Message",
    "select_date": "1. Select Date",
    "select_time": "2. Select Time",
    "request_details": "3. Request Details",
    "job_description": "Job Description*",
    "job_description_placeholder": "Describe what work you need done...",
    "address": "Address*",
    "address_placeholder": "Enter the address where the work will be performed",
    "estimated_price": "Estimated Price",
    "estimated_price_placeholder": "Enter estimated price",
    "add_photo": "Add Photo (optional)",
    "upload_image": "Upload Image",
    "submit_request": "Submit Request",
    "sending": "Sending...",
    "hourly_rate": "Hourly Rate",
    "loading_dates": "Loading available dates...",
    "craftsman_available": "Craftsman is available on the days marked",
    "no_time_slots": "No available time slots",
    "contact_craftsman_message": "Send message to craftsman",
    "contact_message_desc": "Click the button below to contact the craftsman directly via messages.",
    "go_to_messages": "Go to Messages",
    
    // Messages
    "messages_title": "Messages",
    "login_required": "You must be logged in to access messages",
    
    // Error messages
    "profile_access_error": "Profile Access Error",
    "profile_access_message": "You don't have permission to view this profile. This may be due to Row Level Security (RLS) settings in the database.",
    "rls_block_message": "Even though you're logged in as the profile owner, RLS rules may be blocking access. Try logging out and logging back in.",
    "create_profile_again": "Create Profile Again",
    "database_error": "Database Connection Error",
    "database_error_message": "Failed to connect to the database. Try refreshing the page or try again later.",
    "unexpected_error": "An unexpected error occurred",
    "try_again_later": "Try refreshing the page or try again later.",
    "refresh_page": "Refresh Page",
    
    // Benefits page
    "benefits_title": "Benefits for craftsmen",
    "benefit_1_title": "New Business Opportunities",
    "benefit_1_desc": "Gain access to new customers actively seeking services like yours.",
    "benefit_2_title": "Online Presence",
    "benefit_2_desc": "Create a professional profile that increases your visibility and credibility.",
    "benefit_3_title": "Flexible Calendar",
    "benefit_3_desc": "Manage your availability and accept bookings that fit your schedule.",
    "benefit_4_title": "Ratings and Reviews",
    "benefit_4_desc": "Build your reputation through feedback from satisfied customers.",
    "register_now": "Register Now",
    "learn_more": "Learn More",
    
    // Pricing page
    "pricing_title": "Service Pricing",
    "basic_plan": "Basic Plan",
    "basic_price": "€0 / month",
    "basic_description": "Ideal for beginning craftsmen or those who want to try the platform.",
    "premium_plan": "Premium Plan",
    "premium_price": "€19.99 / month",
    "premium_description": "For professional craftsmen who want to maximize their potential.",
    "profile_feature": "Professional Profile",
    "portfolio_feature": "Portfolio Photos",
    "reviews_feature": "Reviews and Ratings",
    "basic_requests": "Limited Requests",
    "premium_requests": "Unlimited Requests",
    "priority_listing": "Priority Listing in Searches",
    "analytics_feature": "Analytics and Reports",
    "premium_support": "Priority Support",
    "featured_profile": "Featured Profile",
    "choose_plan": "Choose Plan",
    "current_plan": "Your Current Plan",
    
    // How it works page
    "how_it_works_title": "How It Works",
    "for_craftsmen_title": "For Craftsmen",
    "step_1_craftsman": "1. Create a Profile",
    "step_1_craftsman_desc": "Create a free profile and showcase your skills and portfolio.",
    "step_2_craftsman": "2. Set Your Availability",
    "step_2_craftsman_desc": "Set your calendar so customers know when you're available.",
    "step_3_craftsman": "3. Get Jobs",
    "step_3_craftsman_desc": "Receive requests and communicate with customers.",
    "for_customers_title": "For Customers",
    "step_1_customer": "1. Find a Craftsman",
    "step_1_customer_desc": "Browse profiles and ratings from other customers.",
    "step_2_customer": "2. Contact the Craftsman",
    "step_2_customer_desc": "Send a message or book an appointment directly through the platform.",
    "step_3_customer": "3. Get Quality Service",
    "step_3_customer_desc": "Enjoy professional service and leave a rating afterward.",
    
    // Privacy page translations
    "privacy_policy": "Privacy Policy",
    "last_updated": "Last updated",
    "may": "May",
    "privacy_intro": "In this privacy policy, we explain how we collect, use, and protect your personal data when you use our platform.",
    "who_processes_data": "Who processes your data",
    "data_controller_desc": "The data controller is the operator of the Majstri.com service. For questions regarding data protection, contact us at",
    "what_data_processed": "What data we process",
    "registration_data_desc": "When registering and using our platform, we collect the following data",
    "full_name": "Full name",
    "email_address": "Email address",
    "phone_number": "Phone number",
    "city_of_residence": "City of residence",
    "data_purpose_desc": "This data is necessary to provide our services, enable communication between users, and ensure safety on the platform.",
    "data_purpose": "Purpose of data processing",
    "data_processing_purposes": "We process your personal data for the following purposes",
    "registration_account": "Registration and account management",
    "profile_creation": "Profile creation and presentation",
    "contact_facilitation": "Facilitating contact between craftsmen and customers",
    "system_messages": "Sending system messages",
    "platform_updates": "Informing about platform news and updates",
    "data_access": "Access to your data",
    "data_access_desc": "Your data is accessible only to authorized employees and collaborators who need this data to fulfill their work duties. We provide data to third parties only to the extent necessary to provide our services or if required by law.",
    "data_retention": "Data retention period",
    "data_retention_desc": "We keep your personal data for the duration of active use of your account and for 2 years after the last activity. After this period, the data is anonymized or deleted.",
    "cookies_usage": "Use of cookies",
    "cookies_usage_desc": "Our website uses cookies to improve user experience, analyze traffic, and provide personalized features. By using our services, you agree to the use of cookies in accordance with our policies.",
    "data_transfer": "Data transfer abroad",
    "data_transfer_desc": "Your personal data may be transferred and stored on servers outside your country, but always in compliance with applicable data protection laws.",
    
    // Terms of service page
    "terms_of_service": "Terms of Service",
    "basic_information": "Basic Information",
    "terms_intro": "These terms of service govern your use of services provided on Majstri.com. If you have any questions, contact us at",
    "registration_age": "Age Restriction",
    "registration_age_desc": "To register and use our platform, you must be at least 18 years old or have reached the age of majority in your country.",
    "user_types": "User Types",
    "platform_user_types": "Our platform distinguishes between two main types of users",
    "user_content": "User Content",
    "user_content_desc": "Users are responsible for all content they upload or share on the platform, including photos, reviews, and profile information.",
    "ratings_reviews": "Ratings and Reviews",
    "ratings_reviews_desc": "Customers may leave ratings and reviews based on their experiences. All reviews must be honest and based on actual experiences.",
    "bookings_communication": "Bookings and Communication",
    "bookings_communication_desc": "All bookings and communication should take place through our platform so that we can ensure service quality and resolve any issues.",
    "responsibility": "Responsibility",
    "responsibility_desc": "The platform serves only as an intermediary between craftsmen and customers. We are not responsible for the quality of work performed or any damages.",
    "payments": "Payments",
    "payments_desc": "Payments for services are agreed directly between the craftsman and customer. The platform may charge fees for certain premium features or services.",
    "account_restrictions": "Account Restrictions",
    "account_restrictions_desc": "We reserve the right to restrict, suspend, or terminate accounts that violate these terms or are involved in fraudulent activities.",
    "promotion_outside": "Promotion Outside the Platform",
    "promotion_outside_desc": "Craftsmen must not redirect customers outside the platform in order to bypass fees or platform rules.",
    "data_protection": "Data Protection",
    "data_protection_desc": "We process personal data in accordance with our privacy policy and applicable legal regulations.",
    "analytics_cookies": "Analytics and Cookies",
    "analytics_cookies_desc": "We use cookies and analytical tools to improve our services and enhance user experience.",
    "final_provisions": "Final Provisions",
    "final_provisions_desc": "We reserve the right to change these terms of service at any time. The current version of the terms can always be found on our website."
  }
};

// LanguageProvider component
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Use browser's preferred language or default to Slovak
  const getBrowserLanguage = (): SupportedLanguage => {
    const lang = navigator.language.split("-")[0];
    if (lang === "sk" || lang === "cs" || lang === "en") {
      return lang as SupportedLanguage;
    }
    return "sk"; // Default to Slovak
  };

  // Get language from localStorage or use browser preference
  const getInitialLanguage = (): SupportedLanguage => {
    const savedLanguage = localStorage.getItem("language") as SupportedLanguage;
    return savedLanguage || getBrowserLanguage();
  };

  const [language, setLanguageState] = useState<SupportedLanguage>(getInitialLanguage);

  // Update language and save to localStorage
  const setLanguage = (newLanguage: SupportedLanguage) => {
    setLanguageState(newLanguage);
    localStorage.setItem("language", newLanguage);
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  useEffect(() => {
    // Set html lang attribute for accessibility
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
