import React, { createContext, useContext, useState, useEffect } from "react";

// Define supported languages
export type SupportedLanguage = "sk" | "cs" | "en";

// Define the context type
type LanguageContextType = {
  language: SupportedLanguage;
  setLanguage: (language: SupportedLanguage) => void;
  t: (key: string) => string;
};

// Create the context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: "sk",
  setLanguage: () => {},
  t: (key: string) => key
});

// Translation data
const translations: Record<SupportedLanguage, Record<string, string>> = {
  sk: {
    // Slovak translations
    "welcome": "Vitajte na Majstri.com",
    "platform_description": "Platforma spájajúca profesionálnych remeselníkov s ľuďmi, ktorí hľadajú ich služby",
    "craftsman": "Som remeselník",
    "customer": "Som zákazník",
    "craftsman_desc": "Prezentujte svoje zručnosti a nájdite nových klientov vo vašom okolí",
    "customer_desc": "Nájdite spoľahlivých remeselníkov pre vaše projekty a vylepšenia domácnosti",
    "login": "Prihlásenie",
    "register": "Registrovať sa",
    "start": "Začať",
    "copyright": "Spájame remeselníkov a zákazníkov",
    
    // Navbar translations
    "home": "Domov",
    "categories": "Kategórie",
    "find_craftsman": "Nájsť remeselníka",
    "jobs": "Zákazky",
    "how_it_works": "Ako to funguje",
    "benefits": "Výhody",
    "messages": "Správy",
    "my_profile": "Môj profil",
    "sign_out": "Odhlásiť sa",
    "sign_in": "Prihlásiť sa",
    
    // Index page translations
    "professional_craftsmen": "Profesionálni remeselníci na jednom mieste",
    "find_best": "Nájdite najlepších",
    "craftsmen": "remeselníkov",
    "platform_connecting": "Platforma, ktorá spája profesionálnych remeselníkov a ľudí, ktorí potrebujú kvalitné služby remeselníkov priamo na Slovensku.",
    "search_profession": "Hľadajte podľa profesie alebo lokality...",
    "search": "Vyhľadať",
    "craftsmen_count": "500+ Remeselníkov",
    "cities_count": "100+ Miest",
    "categories_count": "20+ Kategórií",
    "find_best_craftsmen": "Nájdite najlepších remeselníkov",
    "search_name_craft": "Hľadajte podľa mena alebo remesla...",
    "enter_location": "Zadajte lokalitu...",
    "filter_category": "Filter podľa kategórie",
    "all_categories": "Všetky kategórie",
    "reset": "Reset",
    "view_all_categories": "Zobraziť všetky kategórie",
    "featured_profiles": "Zvýraznené profily sú zobrazené na vrchu",
    "error_loading": "Nastala chyba pri načítaní remeselníkov. Skúste to prosím neskôr.",
    "try_again": "Skúsiť znova",
    "no_craftsmen_found": "Nenašli sa žiadni remeselníci podľa vašich kritérií. Skúste upraviť vyhľadávanie.",
    "show_all_craftsmen": "Zobraziť všetkých remeselníkov",
    
    // About page
    "about_us": "O nás",
    
    // Footer translations
    "for_craftsmen": "Pre remeselníkov",
    "registration": "Registrácia",
    "pricing": "Cenník služieb",
    "registration_benefits": "Výhody registrácie",
    "for_customers": "Pre zákazníkov",
    "find_craftsmen": "Vyhľadať remeselníkov",
    "service_categories": "Kategórie služieb",
    "how_it_works_footer": "Ako to funguje",
    "reviews_ratings": "Hodnotenia a recenzie",
    "company": "Spoločnosť",
    "about_us_footer": "O nás",
    "contact": "Kontakt",
    "privacy": "Ochrana súkromia",
    "terms": "Podmienky používania",
    "all_rights_reserved": "Všetky práva vyhradené",
    
    // Profile translations
    "edit_profile": "Upraviť profil",
    "portfolio": "Portfólio",
    "reviews": "Hodnotenia",
    "calendar": "Kalendár",
    "contact_us": "Kontaktujte nás",
    "loading": "Načítavam...",
    "set_availability_profile": "Nastavte svoju dostupnosť v sekcii \"Kalendár dostupnosti\" vyššie na tejto stránke.",
    "contact_message": "Tu môžete vidieť dostupnosť remeselníka a kontaktovať ho prostredníctvom správy.",
    "send_message": "Poslať správu",
    "book_appointment": "Rezervácia termínu",
    "send_message_tab": "Poslať správu",
    "select_date": "1. Vyberte dátum",
    "select_time": "2. Vyberte čas",
    "request_details": "3. Detaily požiadavky",
    "job_description": "Popis práce*",
    "job_description_placeholder": "Opíšte, akú prácu potrebujete vykonať...",
    "address": "Adresa*",
    "address_placeholder": "Zadajte adresu, kde sa má práca vykonať",
    "estimated_price": "Predpokladaná cena",
    "estimated_price_placeholder": "Zadajte predpokladanú cenu",
    "add_photo": "Pridať fotografiu (voliteľné)",
    "upload_image": "Nahrať obrázok",
    "submit_request": "Odoslať požiadavku",
    "sending": "Odosielam...",
    "hourly_rate": "Hodinová sadzba",
    "loading_dates": "Načítavam dostupné termíny...",
    "craftsman_available": "Remeselník je dostupný v označené dni",
    "no_time_slots": "Žiadne dostupné termíny",
    "contact_craftsman_message": "Poslať správu remeselníkovi",
    "contact_message_desc": "Kliknite na tlačidlo nižšie pre kontaktovanie remeselníka priamo cez správy.",
    "go_to_messages": "Prejsť na správy",
    
    // Messages
    "messages_title": "Správy",
    "login_required": "Pre prístup k správam sa musíte prihlásiť",
    
    // Error messages
    "profile_access_error": "Chyba prístupu k profilu",
    "profile_access_message": "Nemáte oprávnenie na zobrazenie tohto profilu. Toto môže byť spôsobené nastaveniami Row Level Security (RLS) v databáze.",
    "rls_block_message": "Hoci ste prihlásený ako vlastník profilu, RLS pravidlá môžu blokovať prístup. Skúste sa odhlásiť a znova prihlásiť.",
    "create_profile_again": "Vytvoriť profil znova",
    "database_error": "Nastala chyba pripojenia k databáze",
    "database_error_message": "Nepodarilo sa spojiť s databázou. Skúste stránku obnoviť alebo to skúste znova neskôr.",
    "unexpected_error": "Nastala neočakávaná chyba",
    "try_again_later": "Skúste stránku obnoviť alebo to skúste znova neskôr.",
    "refresh_page": "Obnoviť stránku",
    
    // Benefits page
    "benefits_title": "Výhody pre remeselníkov",
    "benefit_1_title": "Nové obchodné príležitosti",
    "benefit_1_desc": "Získajte prístup k novým zákazníkom, ktorí aktívne hľadajú služby ako sú tie vaše.",
    "benefit_2_title": "Online prítomnosť",
    "benefit_2_desc": "Vytvorte si profesionálny profil, ktorý zvýši vašu viditeľnosť a dôveryhodnosť.",
    "benefit_3_title": "Flexibilný kalendár",
    "benefit_3_desc": "Spravujte svoju dostupnosť a prijímajte rezervácie, ktoré vyhovujú vášmu harmonogramu.",
    "benefit_4_title": "Hodnotenia a recenzie",
    "benefit_4_desc": "Budujte svoju reputáciu prostredníctvom spätnej väzby od spokojných zákazníkov.",
    "register_now": "Zaregistrujte sa teraz",
    "learn_more": "Dozvedieť sa viac",
    
    // Pricing page
    "pricing_title": "Cenník služieb",
    "basic_plan": "Základný plán",
    "basic_price": "0 € / mesiac",
    "basic_description": "Ideálne pre začínajúcich remeselníkov alebo tých, ktorí chcú vyskúšať platformu.",
    "premium_plan": "Premium plán",
    "premium_price": "19,99 € / mesiac",
    "premium_description": "Pre profesionálnych remeselníkov, ktorí chcú maximalizovať svoj potenciál.",
    "profile_feature": "Profesionálny profil",
    "portfolio_feature": "Fotografie portfólia",
    "reviews_feature": "Hodnotenia a recenzie",
    "basic_requests": "Obmedzené žiadosti",
    "premium_requests": "Neobmedzené žiadosti",
    "priority_listing": "Prioritné zobrazenie vo vyhľadávaní",
    "analytics_feature": "Analytika a reporty",
    "premium_support": "Prioritná podpora",
    "featured_profile": "Zvýraznený profil",
    "choose_plan": "Vybrať plán",
    "current_plan": "Váš aktuálny plán",
    
    // How it works page
    "how_it_works_title": "Ako to funguje",
    "choose_category": "Vyberte kategóriu",
    "choose_category_desc": "Prechádzajte kategóriami a vyhľadajte typ remeselníka, ktorého potrebujete.",
    "view_profiles": "Prehliadajte profily",
    "view_profiles_desc": "Prehliadajte si detailné profily, hodnotenia a portfóliá remeselníkov.",
    "contact_craftsman_step": "Kontaktujte remeselníka",
    "contact_craftsman_step_desc": "Kontaktujte vybraného remeselníka priamo cez našu platformu.",
    "book_appointment_step": "Rezervujte si termín",
    "book_appointment_step_desc": "Vyberte si termín, ktorý vám vyhovuje, z dostupného kalendára remeselníka.",
    "rate_after_completion": "Ohodnoťte službu",
    "rate_after_completion_desc": "Po dokončení práce zanechajte hodnotenie a pomôžte ostatným zákazníkom.",
    
    "register_create_profile": "Vytvorte si profil",
    "register_create_profile_desc": "Zaregistrujte sa a vytvorte si profesionálny profil, ktorý ukáže vaše zručnosti.",
    "set_availability": "Nastavte dostupnosť",
    "set_availability_desc": "Nastavte svoj kalendár, aby zákazníci videli, kedy ste k dispozícii.",
    "communicate_with_customers": "Komunikujte so zákazníkmi",
    "communicate_with_customers_desc": "Odpovedajte na správy a požiadavky zákazníkov prostredníctvom platformy.",
    "gather_reviews": "Zbierajte hodnotenia",
    "gather_reviews_desc": "Získajte pozitívne hodnotenia a budujte svou online reputaciu.",
    "highlight_profile": "Zvýraznite svoj profil",
    "highlight_profile_desc": "Využite možnosti prémiových funkcií na zvýraznenie vášho profilu vo vyhľadávaní.",
    "more_questions": "Máte ďalšie otázky o tom, ako naša platforma funguje?",
    
    // Categories
    "carpentry": "Stolár",
    "electrician": "Elektrikár",
    "mason": "Murár",
    "plumber": "Inštalatér",
    "painter": "Maliar",
    "flooring": "Podlahár",
    "tinsmiths": "Klampiar",
    "locksmith": "Zámočník",
    "carpenter": "Tesár",
    "gardener": "Záhradník",
    "heating": "Kúrenár",
    "glazier": "Sklenár",
    
    // Terms of service page
    "terms_of_service": "Podmienky používania",
    "basic_information": "Základné informácie",
    "terms_intro": "Tieto podmienky používania upravujú vaše používanie služieb poskytovaných na Majstri.com. Ak máte akékoľvek otázky, kontaktujte nás na",
    "registration_age": "Vekové obmedzenie",
    "registration_age_desc": "Na registráciu a používanie našej platformy musíte mať najmenej 18 rokov alebo dovŕšiť vek plnoletosti vo vašej krajine.",
    "user_types": "Typy používateľov",
    "platform_user_types": "Naša platforma rozlišuje dva hlavné typy používateľov",
    "user_content": "Používateľský obsah",
    "user_content_desc": "Používatelia sú zodpovední za všetok obsah, ktorý nahrajú alebo zdieľajú na platforme, vrátane fotografií, recenzií a profilových informácií.",
    "ratings_reviews": "Hodnotenia a recenzie",
    "ratings_reviews_desc": "Zákazníci môžu zanechávať hodnotenia a recenzie na základe ich skúseností. Všetky recenzie musia byť úprimné a založené na skutočných skúsenostiach.",
    "bookings_communication": "Rezervácie a komunikácia",
    "bookings_communication_desc": "Všetky rezervácie a komunikácia by mali prebiehať prostredníctvom našej platformy, aby sme mohli zabezpečiť kvalitu služieb a riešiť prípadné problémy.",
    "responsibility": "Zodpovednosť",
    "responsibility_desc": "Platforma slúži iba ako sprostredkovateľ medzi remeselníkmi a zákazníkmi. Nenesieme zodpovednosť za kvalitu vykonaných prác ani za prípadné škody.",
    "payments": "Platby",
    "payments_desc": "Platby za služby sú dohodnuté priamo medzi remeselníkom a zákazníkom. Platforma môže účtovať poplatky za určité prémiové funkcie alebo služby.",
    "account_restrictions": "Obmedzenia účtu",
    "account_restrictions_desc": "Vyhradzujeme si právo obmedziť, pozastaviť alebo ukončiť účty, ktoré porušujú tieto podmienky alebo sú zapojené do podvodných aktivít.",
    "promotion_outside": "Propagácia mimo platformy",
    "promotion_outside_desc": "Remeselníci nesmú presmerovať zákazníkov mimo platformy s cieľom obísť poplatky alebo pravidlá platformy.",
    "data_protection": "Ochrana údajov",
    "data_protection_desc": "Spracúvame osobné údaje v súlade s našimi zásadami ochrany osobných údajov a príslušnými právnymi predpismi.",
    "analytics_cookies": "Analytika a cookies",
    "analytics_cookies_desc": "Používame cookies a analytické nástroje na zlepšenie našich služieb a zlepšenie používateľského zážitku.",
    "final_provisions": "Záverečné ustanovenia",
    "final_provisions_desc": "Vyhradzujeme si právo kedykoľvek zmeniť tieto podmienky používania. Aktuálnu verziu podmienok nájdete vždy na našom webe.",
    
    // New categories
    "drywaller": "Sádrokartonista",
    "tiler": "Obkladač",
    "wallpaper": "Tapetár",
    "chimney": "Kominár",
    "tv_tech": "TV/SAT Technik",
    "ac_tech": "Chladiar/Klimatizér",
    "furniture": "Montér nábytku",
    "auto": "Autoelektrikár / Automechanik",
    "metalwork": "Kovovýroba",
    "appliance": "Servis domácich spotrebičov",
    "it": "IT technik",
    "welder": "Zvárač",
    "cleaning": "Upratovacie služby",
    "woodcarving": "Drevorezbár / Umelecký stolár",
    "garden_architect": "Záhradný architekt",
    "window": "Okenár / Montáž okien a dverí",
    "solar": "Montér solárnych panelov",
    "scaffolder": "Lešenár",
    "masseur": "Masér / Masérka",
    "cosmetician": "Kozmetička",
    "nail": "Nechtový dizajnér / Manikérka",
    "pedicure": "Pedikér / Pedikérka",
    "makeup": "Vizážistka / Make-up artist",
    "hairdresser": "Kaderník / Kaderníčka",
    "barber": "Barber",
    "lash": "Lash & Brow artist",
    "tattoo": "Tetovanie / Permanentný make-up",
    "wellness": "Wellness terapeut",
    
    // Profile sections
    "profile_not_found": "Profil nebol nájdený",
    "create_profile": "Vytvoriť profil",
    "profile_creation_error": "Chyba pri vytváraní profilu",
    "profile_completion": "Dokončenie profilu",
    "user_type_question": "Aký typ používateľa ste?",
    "years_experience": "Roky skúseností",
    "specialization": "Špecializácia",
    "about_me": "O mne",
    "projects": "Projekty",
    "no_projects": "Zatiaľ nie sú pridané žiadne projekty",
    "add_project": "Pridať projekt",
    "portfolio_images": "Obrázky portfólia",
    "upload_portfolio": "Nahrať obrázky portfólia",
    "add_review": "Pridať hodnotenie",
    "select_craftsman": "Vyberte remeselníka",
    "write_review": "Napíšte recenziu",
    "rating": "Hodnotenie",
    "comment": "Komentár",
    "submit_review": "Odoslať hodnotenie",
    "edit_review": "Upraviť hodnotenie",
    "delete_review": "Vymazať hodnotenie",
    "reply": "Odpovedať",
    "edit_reply": "Upraviť odpoveď",
    "delete_reply": "Vymazať odpoveď",
    "save_changes": "Uložiť zmeny",
    "cancel": "Zrušiť",
    "availability_settings": "Nastavenia dostupnosti",
    "availability_calendar": "Kalendár dostupnosti",
    "set_time_slots": "Nastaviť časové sloty",
    "unavailable": "Nedostupný",
    "available_all_day": "Dostupný celý deň",
    "custom_hours": "Vlastné hodiny",
    "start_time": "Čas začiatku",
    "end_time": "Čas konca",
    "update_availability": "Aktualizovať dostupnosť",
    "availability_updated": "Dostupnosť bola aktualizovaná",
    "error_updating": "Chyba pri aktualizácii",
    
    // Reviews and profile sections
    "write_comment_placeholder": "Napíšte váš názor na prácu remeselníka...",
    "anonymous_customer": "Anonymný zákazník",
    "craftsman_response": "Odpoveď remeselníka",
    "no_reviews": "Zatiaľ nie sú žiadne hodnotenia",
    "be_first": "Buďte prvý, kto ohodnotí tohto remeselníka",
    "based_on": "Na základe",
    "ratings": "hodnotení",
    "personal_info": "Osobné informácie",
    "business_info": "Informácie o podnikaní",
    "location_label": "Lokalita",
    "phone_label": "Telefón",
    "email_label": "E-mail",
    "save_profile": "Uložiť profil",
    "saving": "Ukladám...",
    "profile_updated": "Profil bol aktualizovaný",
    "error_saving": "Chyba pri ukladaní profilu",
    
    // Chat and messages
    "conversation_with": "Konverzácia s",
    "new_message": "Nová správa",
    "select_recipient": "Vyberte príjemcu",
    "message_placeholder": "Napíšte správu...",
    "send": "Odoslať",
    "no_conversations": "Zatiaľ nemáte žiadne konverzácie",
    "start_conversation": "Začnite konverzáciu s remeselníkom alebo zákazníkom",
    "no_messages": "Zatiaľ nie sú žiadne správy",
    "type_message": "Napíšte správu pre začatie konverzácie",
    "message_sent": "Správa odoslaná",
    "error_sending": "Chyba pri odosielaní správy",
    "delete_conversation": "Vymazať konverzáciu",
    "archive_conversation": "Archivovať konverzáciu",
    "confirm_delete": "Naozaj chcete vymazať túto konverzáciu?",
    "yes_delete": "Áno, vymazať",
  },
  cs: {
    // Czech translations
    "welcome": "Vítejte na Majstri.com",
    "platform_description": "Platforma spojující profesionální řemeslníky s lidmi, kteří hledají jejich služby",
    "craftsman": "Jsem řemeslník",
    "customer": "Jsem zákazník",
    "craftsman_desc": "Prezentujte své dovednosti a najděte nové klienty ve vašem okolí",
    "customer_desc": "Najděte spolehlivé řemeslníky pro vaše projekty a vylepšení domácnosti",
    "login": "Přihlášení",
    "register": "Registrovat se",
    "start": "Začít",
    "copyright": "Spojujeme řemeslníky a zákazníky",
    
    // Navbar translations
    "home": "Domů",
    "categories": "Kategorie",
    "find_craftsman": "Najít řemeslníka",
    "jobs": "Zakázky",
    "how_it_works": "Jak to funguje",
    "benefits": "Výhody",
    "messages": "Zprávy",
    "my_profile": "Můj profil",
    "sign_out": "Odhlásit se",
    "sign_in": "Přihlásit se",
    
    // Index page translations
    "professional_craftsmen": "Profesionální řemeslníci na jednom místě",
    "find_best": "Najděte nejlepší",
    "craftsmen": "řemeslníky",
    "platform_connecting": "Platforma, která spojuje profesionální řemeslníky a lidi, kteří potřebují kvalitní služby řemeslníků přímo v Česku.",
    "search_profession": "Hledejte podle profese nebo lokality...",
    "search": "Vyhledat",
    "craftsmen_count": "500+ Řemeslníků",
    "cities_count": "100+ Měst",
    "categories_count": "20+ Kategorií",
    "find_best_craftsmen": "Najděte nejlepší řemeslníky",
    "search_name_craft": "Hledejte podle jména nebo řemesla...",
    "enter_location": "Zadejte lokalitu...",
    "filter_category": "Filtrovat podle kategorie",
    "all_categories": "Všechny kategorie",
    "reset": "Reset",
    "view_all_categories": "Zobrazit všechny kategorie",
    "featured_profiles": "Zvýrazněné profily jsou zobrazeny nahoře",
    "error_loading": "Nastala chyba při načítání řemeslníků. Zkuste to prosím později.",
    "try_again": "Zkusit znovu",
    "no_craftsmen_found": "Nenašli se žádní řemeslníci podle vašich kritérií. Zkuste upravit vyhledávání.",
    "show_all_craftsmen": "Zobrazit všechny řemeslníky",
    
    // About page
    "about_us": "O nás",
    
    // Footer translations
    "for_craftsmen": "Pro řemeslníky",
    "registration": "Registrace",
    "pricing": "Ceník služeb",
    "registration_benefits": "Výhody registrace",
    "for_customers": "Pro zákazníky",
    "find_craftsmen": "Vyhledat řemeslníky",
    "service_categories": "Kategorie služeb",
    "how_it_works_footer": "Jak to funguje",
    "reviews_ratings": "Hodnocení a recenze",
    "company": "Společnost",
    "about_us_footer": "O nás",
    "contact": "Kontakt",
    "privacy": "Ochrana soukromí",
    "terms": "Podmínky používání",
    "all_rights_reserved": "Všechna práva vyhrazena",
    
    // Profile translations
    "edit_profile": "Upravit profil",
    "portfolio": "Portfolio",
    "reviews": "Hodnocení",
    "calendar": "Kalendář",
    "contact_us": "Kontaktujte nás",
    "loading": "Načítám...",
    "set_availability": "Nastavte svou dostupnost v sekci \"Kalendář dostupnosti\" výše na této stránce.",
    "contact_message": "Zde můžete vidět dostupnost řemeslníka a kontaktovat ho prostřednictvím zprávy.",
    "send_message": "Poslat zprávu",
    "book_appointment": "Rezervace termínu",
    "send_message_tab": "Poslat zprávu",
    "select_date": "1. Vyberte datum",
    "select_time": "2. Vyberte čas",
    "request_details": "3. Detaily požadavku",
    "job_description": "Popis práce*",
    "job_description_placeholder": "Popište, jakou práci potřebujete vykonat...",
    "address": "Adresa*",
    "address_placeholder": "Zadejte adresu, kde se má práce vykonat",
    "estimated_price": "Předpokládaná cena",
    "estimated_price_placeholder": "Zadejte předpokládanou cenu",
    "add_photo": "Přidat fotografii (volitelné)",
    "upload_image": "Nahrát obrázek",
    "submit_request": "Odeslat požadavek",
    "sending": "Odesílám...",
    "hourly_rate": "Hodinová sazba",
    "loading_dates": "Načítám dostupné termíny...",
    "craftsman_available": "Řemeslník je dostupný v označené dny",
    "no_time_slots": "Žádné dostupné termíny",
    "contact_craftsman": "Poslat zprávu řemeslníkovi",
    "contact_message_desc": "Klikněte na tlačítko níže pro kontaktování řemeslníka přímo přes zprávy.",
    "go_to_messages": "Přejít na zprávy",
    
    // Messages
    "messages_title": "Zprávy",
    "login_required": "Pro přístup ke zprávám se musíte přihlásit",
    
    // Error messages
    "profile_access_error": "Chyba přístupu k profilu",
    "profile_access_message": "Nemáte oprávnění k zobrazení tohoto profilu. Toto může být způsobeno nastavením Row Level Security (RLS) v databázi.",
    "rls_block_message": "Přestože jste přihlášen jako vlastník profilu, RLS pravidla mohou blokovat přístup. Zkuste se odhlásit a znovu přihlásit.",
    "create_profile_again": "Vytvořit profil znovu",
    "database_error": "Nastala chyba připojení k databázi",
    "database_error_message": "Nepodařilo se spojit s databází. Zkuste stránku obnovit nebo to zkuste znovu později.",
    "unexpected_error": "Nastala neočekávaná chyba",
    "try_again_later": "Zkuste stránku obnovit nebo to zkuste znovu později.",
    "refresh_page": "Obnovit stránku",
    
    // Benefits page
    "benefits_title": "Výhody pro řemeslníky",
    "benefit_1_title": "Nové obchodní příležitosti",
    "benefit_1_desc": "Získejte přístup k novým zákazníkům, kteří aktivně hledají služby jako jsou ty vaše.",
    "benefit_2_title": "Online přítomnost",
    "benefit_2_desc": "Vytvořte si profesionální profil, který zvýší vaši viditelnost a důvěryhodnost.",
    "benefit_3_title": "Flexibilní kalendář",
    "benefit_3_desc": "Spravujte svou dostupnost a přijímejte rezervace, které vyhovují vašemu harmonogramu.",
    "benefit_4_title": "Hodnocení a recenze",
    "benefit_4_desc": "Budujte svou reputaci prostřednictvím zpětné vazby od spokojených zákazníků.",
    "register_now": "Zaregistrujte se nyní",
    "learn_more": "Dozvědět se více",
    
    // Pricing page
    "pricing_title": "Ceník služeb",
    "basic_plan": "Základní plán",
    "basic_price": "0 € / měsíc",
    "basic_description": "Ideální pro začínající řemeslníky nebo ty, kteří chtějí vyzkoušet platformu.",
    "premium_plan": "Premium plán",
    "premium_price": "19,99 € / měsíc",
    "premium_description": "Pro profesionální řemeslníky, kteří chtějí maximalizovat svůj potenciál.",
    "profile_feature": "Profesionální profil",
    "portfolio_feature": "Fotografie portfolia",
    "reviews_feature": "Hodnocení a recenze",
    "basic_requests": "Omezené žádosti",
    "premium_requests": "Neomezené žádosti",
    "priority_listing": "Prioritní zobrazení ve vyhledávání",
    "analytics_feature": "Analytika a reporty",
    "premium_support": "Prioritní podpora",
    "featured_profile": "Zvýrazněný profil",
    "choose_plan": "Vybrat plán",
    "current_plan": "Váš aktuální plán",
    
    // How it works page
    "how_it_works_title": "Jak to funguje",
    "for_craftsmen_title": "Pro řemeslníky",
    "step_1_craftsman": "1. Vytvořte si profil",
    "step_1_craftsman_desc": "Vytvořte si bezplatný profil a ukažte své dovednosti a portfolio.",
    "step_2_craftsman": "2. Nastavte svou dostupnost",
    "step_2_craftsman_desc": "Nastavte svůj kalendář, aby zákazníci věděli, kdy jste k dispozici.",
    "step_3_craftsman": "3. Získejte zakázky",
    "step_3_craftsman_desc": "Přijímejte žádosti a komunikujte se zákazníky.",
    "for_customers_title": "Pro zákazníky",
    "step_1_customer": "1. Vyhledejte řemeslníka",
    "step_1_customer_desc": "Prohlížejte si profily řemeslníků a hodnocení od jiných zákazníků.",
    "step_2_customer": "2. Kontaktujte řemeslníka",
    "step_2_customer_desc": "Pošlete zprávu nebo si zarezervujte termín přímo přes platformu.",
    "step_3_customer": "3. Získejte kvalitní službu",
